<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <AssemblyName>Skyline.DataMiner.Utils.DocumentHub</AssemblyName>
    <RootNamespace>Skyline.DataMiner.Utils.DocumentHub</RootNamespace>
    <PackageVersion>1.0.1</PackageVersion>
    <Version>1.0.1</Version>
    <PackageTags>Skyline;DataMiner</PackageTags>
    <PackageProjectUrl>https://skyline.be</PackageProjectUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
    <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
    <PackageIcon>Icon.png</PackageIcon>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Authors>SkylineCommunications</Authors>
    <Company>Skyline Communications</Company>
    <Description>NuGet Class Library API to interact with DocumentHub functionality.</Description>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/SkylineCommunications/SLC-App-DocumentHub-API</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="" />
    <None Include="LICENSE.txt" Pack="true" PackagePath="" />
    <None Include="nuget\Icon.png" Pack="true" PackagePath="" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="Azure.Identity" Version="1.16.0" />
    <PackageReference Include="Microsoft.Graph" Version="4.36.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="Skyline.DataMiner.Dev.Common" Version="10.5.12.2" />
    <PackageReference Include="Skyline.DataMiner.Utils.SecureCoding" Version="2.2.1" />
    <PackageReference Include="Skyline.DataMiner.Utils.SecureCoding.Analyzers" Version="2.2.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="System.Drawing.Common" Version="10.0.1" />
  </ItemGroup>
</Project>
