//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Skyline.DataMiner.SDM.CodeGenerator package.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Skyline.DataMiner.Solutions.DocumentHub.SDM.Repositories.DomSource
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using Skyline.DataMiner.Net;
    using Skyline.DataMiner.Net.Apps.DataMinerObjectModel;
    using Skyline.DataMiner.Net.Apps.Sections.Sections;
    using Skyline.DataMiner.Net.Helper;
    using Skyline.DataMiner.Net.ManagerStore;
    using Skyline.DataMiner.Net.Messages;
    using Skyline.DataMiner.Net.Messages.SLDataGateway;
    using Skyline.DataMiner.Net.Sections;
    using Skyline.DataMiner.Net.SubscriptionFilters;
    using Skyline.DataMiner.SDM;
    using Skyline.DataMiner.Solutions.DocumentHub.SDM.Models;
    using SLDataGateway.API.Querying;
    using SLDataGateway.API.Types.Querying;

    internal partial class DomSourceDomRepository : IRepository<DomSource>
    {
        private readonly IConnection connection;
        private readonly DomHelper helper;
        public DomSourceDomRepository(IConnection connection)
        {
            this.connection = connection;
            this.helper = new DomHelper(connection.HandleMessages, Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.DomSourceDomMapper.ModuleId);
        }

        public DomSource Create(DomSource createObject)
        {
            if (createObject is null)
            {
                throw new ArgumentNullException(nameof(createObject));
            }

            var instance = ToInstance(createObject);
            instance = helper.DomInstances.Create(instance);
            return FromInstance(instance);
        }

        public IReadOnlyCollection<DomSource> CreateOrUpdate(IEnumerable<DomSource> items)
        {
            if (items is null || !items.Any())
            {
                return Array.Empty<DomSource>();
            }

            var successful = new List<DomSource>();
            var exceptionBuilder = new SdmBulkCrudException<DomSource>.Builder();
            var objects = items.ToDictionary(obj => obj.Identifier);
            foreach (var batch in items.Select(ToInstance).Batch(helper.DomInstances.MaxAmountBulkOperation))
            {
                helper.DomInstances.TryCreateOrUpdate(batch.ToList(), out var result);
                foreach (var failure in result.UnsuccessfulIds)
                {
                    exceptionBuilder.AddFailed(objects[failure.Id.ToString()], new CrudFailedException(result.TraceDataPerItem[failure]));
                }

                foreach (var success in result.SuccessfulItems)
                {
                    var item = FromInstance(success);
                    exceptionBuilder.AddSuccessful(item);
                    successful.Add(item);
                }
            }

            if (exceptionBuilder.HasFailure)
            {
                throw exceptionBuilder.Build();
            }

            return successful;
        }

        public long Count(FilterElement<DomSource> filter)
        {
            if (filter is null)
            {
                throw new ArgumentNullException(nameof(filter));
            }

            var domFilter = TranslateFullFilter(filter);
            domFilter = domFilter.AND(DomInstanceExposers.DomDefinitionId.Equal(Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.DomSourceDomMapper.DomDefinitionId.Id));
            return helper.DomInstances.Count(domFilter);
        }

        public long Count(IQuery<DomSource> query)
        {
            if (query is null)
            {
                throw new ArgumentNullException(nameof(query));
            }

            var domFilter = TranslateFullFilter(query.Filter);
            domFilter = domFilter.AND(DomInstanceExposers.DomDefinitionId.Equal(Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.DomSourceDomMapper.DomDefinitionId.Id));
            var domOrder = TranslateFullOrderBy(query.Order);
            var domQuery = query.WithFilter(domFilter).WithOrder(domOrder);
            return helper.DomInstances.Count(domQuery);
        }

        public IEnumerable<DomSource> Read(FilterElement<DomSource> filter)
        {
            if (filter is null)
            {
                throw new ArgumentNullException(nameof(filter));
            }

            var domFilter = TranslateFullFilter(filter);
            return Read(domFilter);
        }

        public IEnumerable<DomSource> Read(IQuery<DomSource> query)
        {
            if (query is null)
            {
                throw new ArgumentNullException(nameof(query));
            }

            var domFilter = TranslateFullFilter(query.Filter);
            var domOrder = TranslateFullOrderBy(query.Order);
            var domQuery = query.WithFilter(domFilter).WithOrder(domOrder);
            return Read(domQuery);
        }

        public IEnumerable<IPagedResult<DomSource>> ReadPaged(FilterElement<DomSource> filter)
        {
            return ReadPaged(filter, 500);
        }

        public IEnumerable<IPagedResult<DomSource>> ReadPaged(FilterElement<DomSource> filter, int pageSize)
        {
            if (filter is null)
            {
                throw new ArgumentNullException(nameof(filter));
            }

            if (pageSize <= 0)
            {
                throw new ArgumentOutOfRangeException(nameof(pageSize), "The page size must be 1 or higher");
            }

            var domFilter = TranslateFullFilter(filter);
            var paging = ReadPaged(domFilter, pageSize).GetEnumerator();
            var moveNext = paging.MoveNext();
            var i = 0;
            while (moveNext)
            {
                var page = paging.Current.ToList();
                moveNext = paging.MoveNext();
                var result = new PagedResult<DomSource>(page, i, pageSize, moveNext);
                yield return result;
                i++;
            }
        }

        public IEnumerable<IPagedResult<DomSource>> ReadPaged(IQuery<DomSource> query)
        {
            return ReadPaged(query, 500);
        }

        public IEnumerable<IPagedResult<DomSource>> ReadPaged(IQuery<DomSource> query, int pageSize)
        {
            if (query is null)
            {
                throw new ArgumentNullException(nameof(query));
            }

            if (pageSize <= 0)
            {
                throw new ArgumentOutOfRangeException(nameof(pageSize), "The page size must be 1 or higher");
            }

            var domFilter = TranslateFullFilter(query.Filter);
            var domOrder = TranslateFullOrderBy(query.Order);
            var domQuery = query.WithFilter(domFilter).WithOrder(domOrder);
            var paging = ReadPaged(domQuery, pageSize).GetEnumerator();
            var moveNext = paging.MoveNext();
            var i = 0;
            while (moveNext)
            {
                var page = paging.Current.ToList();
                moveNext = paging.MoveNext();
                var result = new PagedResult<DomSource>(page, i, pageSize, moveNext);
                yield return result;
                i++;
            }
        }

        public DomSource Update(DomSource updateObject)
        {
            if (updateObject is null)
            {
                throw new ArgumentNullException(nameof(updateObject));
            }

            var instance = ToInstance(updateObject);
            instance = helper.DomInstances.Update(instance);
            return FromInstance(instance);
        }

        public void Delete(DomSource deleteObject)
        {
            if (deleteObject is null)
            {
                throw new ArgumentNullException(nameof(deleteObject));
            }

            var instance = ToInstance(deleteObject);
            helper.DomInstances.Delete(instance);
        }

        public void Delete(IEnumerable<DomSource> deleteObjects)
        {
            if (deleteObjects is null || !deleteObjects.Any())
            {
                return;
            }

            var exceptionBuilder = new SdmBulkCrudException<DomSource>.Builder();
            var objects = deleteObjects.ToDictionary(obj => obj.Identifier);
            foreach (var batch in deleteObjects.Select(ToInstance).Batch(helper.DomInstances.MaxAmountBulkOperation))
            {
                helper.DomInstances.TryDelete(batch.ToList(), out var result);
                foreach (var failure in result.UnsuccessfulIds)
                {
                    exceptionBuilder.AddFailed(objects[failure.Id.ToString()], new CrudFailedException(result.TraceDataPerItem[failure]));
                }

                foreach (var success in result.SuccessfulIds)
                {
                    exceptionBuilder.AddSuccessful(objects[success.Id.ToString()]);
                }
            }

            if (exceptionBuilder.HasFailure)
            {
                throw exceptionBuilder.Build();
            }
        }

        private IEnumerable<DomSource> Read(FilterElement<DomInstance> domFilter)
        {
            if (domFilter is null)
            {
                throw new ArgumentNullException(nameof(domFilter));
            }

            domFilter = domFilter.AND(DomInstanceExposers.DomDefinitionId.Equal(Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.DomSourceDomMapper.DomDefinitionId.Id));
            var domInstances = helper.DomInstances.Read(domFilter);
            return domInstances.Select(FromInstance);
        }

        private IEnumerable<DomSource> Read(IQuery<DomInstance> domQuery)
        {
            if (domQuery is null)
            {
                throw new ArgumentNullException(nameof(domQuery));
            }

            var domFilter = domQuery.Filter.AND(DomInstanceExposers.DomDefinitionId.Equal(Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.DomSourceDomMapper.DomDefinitionId.Id));
            domQuery = domQuery.WithFilter(domFilter);
            var domInstances = helper.DomInstances.Read(domQuery);
            return domInstances.Select(FromInstance);
        }

        private IEnumerable<IEnumerable<DomSource>> ReadPaged(FilterElement<DomInstance> domFilter, int pageSize)
        {
            if (domFilter is null)
            {
                throw new ArgumentNullException(nameof(domFilter));
            }

            domFilter = domFilter.AND(DomInstanceExposers.DomDefinitionId.Equal(Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.DomSourceDomMapper.DomDefinitionId.Id));
            var pagingHelper = helper.DomInstances.PreparePaging(domFilter, pageSize);
            while (pagingHelper.MoveToNextPage())
            {
                yield return pagingHelper.GetCurrentPage().Select(FromInstance);
            }
        }

        private IEnumerable<IEnumerable<DomSource>> ReadPaged(IQuery<DomInstance> domQuery, int pageSize)
        {
            if (domQuery is null)
            {
                throw new ArgumentNullException(nameof(domQuery));
            }

            var domFilter = domQuery.Filter.AND(DomInstanceExposers.DomDefinitionId.Equal(Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.DomSourceDomMapper.DomDefinitionId.Id));
            domQuery = domQuery.WithFilter(domFilter);
            var pagingHelper = helper.DomInstances.PreparePaging(domQuery, pageSize);
            while (pagingHelper.MoveToNextPage())
            {
                yield return pagingHelper.GetCurrentPage().Select(FromInstance);
            }
        }

        private FilterElement<DomInstance> TranslateFullFilter(FilterElement<DomSource> filter)
        {
            if (filter is null)
            {
                throw new ArgumentNullException(nameof(filter));
            }

            FilterElement<DomInstance> translated;
            if (filter is ANDFilterElement<DomSource> and)
            {
                translated = new ANDFilterElement<DomInstance>(and.subFilters.Select(TranslateFullFilter).ToArray());
            }
            else if (filter is ORFilterElement<DomSource> or)
            {
                translated = new ORFilterElement<DomInstance>(or.subFilters.Select(TranslateFullFilter).ToArray());
            }
            else if (filter is NOTFilterElement<DomSource> not)
            {
                translated = new NOTFilterElement<DomInstance>(TranslateFullFilter(not));
            }
            else if (filter is TRUEFilterElement<DomSource>)
            {
                translated = new TRUEFilterElement<DomInstance>();
            }
            else if (filter is FALSEFilterElement<DomSource>)
            {
                translated = new FALSEFilterElement<DomInstance>();
            }
            else if (filter is ManagedFilterIdentifier managedFilter)
            {
                translated = TranslateFilter(managedFilter);
            }
            else
            {
                throw new NotSupportedException($"Unsupported filter: {filter}");
            }

            return translated;
        }

        private IOrderBy TranslateFullOrderBy(IOrderBy order)
        {
            if (order is null)
            {
                throw new ArgumentNullException(nameof(order));
            }

            var translatedElements = new List<IOrderByElement>();
            foreach (var orderByElement in order.Elements)
            {
                var translated = TranslateOrderBy(orderByElement);
                translatedElements.Add(translated);
            }

            return new OrderBy(translatedElements);
        }

        private FilterElement<DomInstance> TranslateFilter(ManagedFilterIdentifier managedFilter)
        {
            if (managedFilter is null)
            {
                throw new ArgumentNullException(nameof(managedFilter));
            }

            var fieldName = managedFilter.getFieldName().fieldName;
            var comparer = managedFilter.getComparer();
            var value = managedFilter.getValue();
            var translated = CreateFilter(fieldName, comparer, value);
            return translated;
        }

        private IOrderByElement TranslateOrderBy(IOrderByElement orderByElement)
        {
            if (orderByElement is null)
            {
                throw new ArgumentNullException(nameof(orderByElement));
            }

            var fieldName = orderByElement.Exposer.fieldName;
            var sortOrder = orderByElement.SortOrder;
            var naturalSort = orderByElement.Options.NaturalSort;
            var translated = CreateOrderBy(fieldName, sortOrder, naturalSort);
            return translated;
        }

        private DomSource FromInstance(DomInstance instance)
        {
            var obj = new DomSource
            {
                Identifier = instance.ID.Id.ToString()
            };
            var _domsourcepropertiesSection = instance.Sections.FirstOrDefault(s => s.SectionDefinitionID.Equals(Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.DomSourceDomMapper.DomSourceProperties.SectionDefinitionId));
            if (_domsourcepropertiesSection != default)
            {
                var _name = _domsourcepropertiesSection.GetValue<string>(Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.DomSourceDomMapper.DomSourceProperties.Name);
                if (_name != null)
                {
                    obj.Name = _name.Value;
                }

                var _module = _domsourcepropertiesSection.GetValue<string>(Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.DomSourceDomMapper.DomSourceProperties.Module);
                if (_module != null)
                {
                    obj.Module = _module.Value;
                }

                var _networksharepath = _domsourcepropertiesSection.GetValue<string>(Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.DomSourceDomMapper.DomSourceProperties.NetworkSharePath);
                if (_networksharepath != null)
                {
                    obj.NetworkSharePath = _networksharepath.Value;
                }

                var _credential = _domsourcepropertiesSection.GetValue<string>(Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.DomSourceDomMapper.DomSourceProperties.Credential);
                if (_credential != null)
                {
                    obj.Credential = _credential.Value;
                }
            }

            return obj;
        }

        private DomInstance ToInstance(DomSource obj)
        {
            Guid id = default(Guid);
            if (!String.IsNullOrEmpty(obj.Identifier))
            {
                id = Guid.Parse(obj.Identifier);
            }
            else
            {
                id = Guid.NewGuid();
            }

            var instance = new DomInstance
            {
                DomDefinitionId = Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.DomSourceDomMapper.DomDefinitionId,
                ID = new DomInstanceId(id)
                {
                    ModuleId = Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.DomSourceDomMapper.ModuleId
                }
            };
            var _domsourceproperties = new Section(Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.DomSourceDomMapper.DomSourceProperties.SectionDefinitionId);
            if (obj.Name != default)
            {
                _domsourceproperties.AddOrUpdateValue<string>(Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.DomSourceDomMapper.DomSourceProperties.Name, Convert.ToString(obj.Name));
            }

            if (obj.Module != default)
            {
                _domsourceproperties.AddOrUpdateValue<string>(Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.DomSourceDomMapper.DomSourceProperties.Module, Convert.ToString(obj.Module));
            }

            if (obj.NetworkSharePath != default)
            {
                _domsourceproperties.AddOrUpdateValue<string>(Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.DomSourceDomMapper.DomSourceProperties.NetworkSharePath, Convert.ToString(obj.NetworkSharePath));
            }

            if (obj.Credential != default)
            {
                _domsourceproperties.AddOrUpdateValue<string>(Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.DomSourceDomMapper.DomSourceProperties.Credential, Convert.ToString(obj.Credential));
            }

            instance.Sections.Add(_domsourceproperties);
            return instance;
        }

        private FilterElement<DomInstance> CreateFilter(string fieldName, Comparer comparer, object value)
        {
            switch (fieldName)
            {
                case "Identifier":
                    {
                        if (string.IsNullOrEmpty((string)value))
                        {
                            throw new ArgumentException("Cannot filter DomSource by Identifier: the provided value is null or empty.");
                        }

                        return FilterElementFactory.Create<DomInstance>(DomInstanceExposers.Id, comparer, Guid.Parse((string)value));
                    }
                case "Name":
                    return new DynamicManagedListFilter<DomInstance, object>(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.DomSourceDomMapper.DomSourceProperties.Name), comparer, (string)value);
                case "Module":
                    return new DynamicManagedListFilter<DomInstance, object>(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.DomSourceDomMapper.DomSourceProperties.Module), comparer, (string)value);
                case "NetworkSharePath":
                    return new DynamicManagedListFilter<DomInstance, object>(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.DomSourceDomMapper.DomSourceProperties.NetworkSharePath), comparer, (string)value);
                case "Credential":
                    return new DynamicManagedListFilter<DomInstance, object>(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.DomSourceDomMapper.DomSourceProperties.Credential), comparer, (string)value);
                default:
                    throw new NotImplementedException();
            }
        }

        private IOrderByElement CreateOrderBy(string fieldName, SortOrder sortOrder, bool naturalSort = false)
        {
            switch (fieldName)
            {
                case "Identifier":
                    return OrderByElementFactory.Create(DomInstanceExposers.Id, sortOrder, naturalSort);
                case "Name":
                    return OrderByElementFactory.Create(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.DomSourceDomMapper.DomSourceProperties.Name), sortOrder, naturalSort);
                case "Module":
                    return OrderByElementFactory.Create(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.DomSourceDomMapper.DomSourceProperties.Module), sortOrder, naturalSort);
                case "NetworkSharePath":
                    return OrderByElementFactory.Create(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.DomSourceDomMapper.DomSourceProperties.NetworkSharePath), sortOrder, naturalSort);
                case "Credential":
                    return OrderByElementFactory.Create(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.DomSourceDomMapper.DomSourceProperties.Credential), sortOrder, naturalSort);
                default:
                    throw new NotImplementedException();
            }
        }
    }
}