//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Dom Code Generator automation script.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace DomHelpers.SlcDocumenthub
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using Skyline.DataMiner.Net.Apps.DataMinerObjectModel;
    using Skyline.DataMiner.Net.Messages;

    /// <summary>
    /// Represents a wrapper class for accessing a DocumentCategoryInstance DOM instance.
    /// The <see cref="DocumentCategoryInstance"/> class provides simplified access to the data and functionality of the underlying DOM instance, allowing for easier manipulation and retrieval of data from DOM.
    /// </summary>
    public partial class DocumentCategoryInstance : DomInstanceBase
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DocumentCategoryInstance"/> class. Creates an empty <see cref="DocumentCategoryInstance"/> instance with default settings.
        /// </summary>
        public DocumentCategoryInstance() : base(SlcDocumenthubIds.Definitions.DocumentCategory)
        {
            InitializeProperties();
            AfterLoad();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DocumentCategoryInstance"/> class. Creates an empty <see cref="DocumentCategoryInstance"/> instance with default settings and a specific ID.
        /// </summary>
        public DocumentCategoryInstance(Guid id) : base(SlcDocumenthubIds.Definitions.DocumentCategory, id)
        {
            InitializeProperties();
            AfterLoad();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DocumentCategoryInstance"/> class using the specified <paramref name="domInstance"/> for initializing the object.
        /// </summary>
        /// <param name="domInstance">The <see cref="DomInstance"/> object that provides data for initializing the <see cref="DocumentCategoryInstance"/>. If the section is <c>null</c>, the constructor will not perform any initialization.</param>
        public DocumentCategoryInstance(DomInstance domInstance) : base(domInstance)
        {
            if (!domInstance.DomDefinitionId.Equals(SlcDocumenthubIds.Definitions.DocumentCategory))
                throw new ArgumentException($"The given domInstance, is not of type '{nameof(SlcDocumenthubIds.Definitions.DocumentCategory)}'", nameof(domInstance));
            InitializeProperties();
            AfterLoad();
        }

        /// <summary>
        /// Gets or sets the CategoryInfo section of the DOM Instance.
        /// </summary>
        public CategoryInfoSection CategoryInfo { get; set; }

        public static explicit operator DocumentCategoryInstance(DomInstance instance)
        {
            return new DocumentCategoryInstance(instance);
        }

        /// <summary>
        /// Creates a deep copy of the current <see cref="DocumentCategoryInstance"/>.
        /// </summary>
        /// <returns>A new <see cref="DocumentCategoryInstance"/> object that is a deep copy of this instance.</returns>
        public DocumentCategoryInstance Clone()
        {
            return new DocumentCategoryInstance((DomInstance)this.ToInstance().Clone());
        }

        /// <summary>
        /// Creates a duplicate of the current <see cref="DocumentCategoryInstance"/> with a new id.
        /// </summary>
        /// <returns>A new <see cref="DocumentCategoryInstance"/> object that is a copy of this instance but with a different id.</returns>
        public DocumentCategoryInstance Duplicate()
        {
            var instance = (DomInstance)this.ToInstance().Clone();
            instance.ID = new DomInstanceId(Guid.NewGuid())
            { ModuleId = ModuleId };
            foreach (var section in instance.Sections)
            {
                section.ID = new Skyline.DataMiner.Net.Sections.SectionID(Guid.NewGuid());
            }

            return new DocumentCategoryInstance(instance);
        }

        /// <inheritdoc />
        protected sealed override DomInstance InternalToInstance()
        {
            domInstance.Sections.Clear();
            domInstance.Sections.Add(CategoryInfo.ToSection());
            return domInstance;
        }

        /// <inheritdoc />
        public sealed override void Save(DomHelper helper)
        {
            var exist = helper.DomInstances.Read(DomInstanceExposers.Id.Equal(domInstance.ID)).FirstOrDefault();
            var instance = ToInstance();
            if (exist == null)
            {
                domInstance = helper.DomInstances.Create(instance);
            }
            else
            {
                domInstance = helper.DomInstances.Update(instance);
            }
        }

        protected sealed override void InitializeProperties()
        {
            var _categoryInfo = domInstance.Sections.FirstOrDefault(section => section.SectionDefinitionID.Equals(SlcDocumenthubIds.Sections.CategoryInfo.Id));
            if (_categoryInfo is null)
            {
                CategoryInfo = new CategoryInfoSection();
            }
            else
            {
                CategoryInfo = new CategoryInfoSection(_categoryInfo);
            }
        }
    }
}