//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Dom Code Generator automation script.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace DomHelpers.SlcDocumenthub
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using Skyline.DataMiner.Net.Apps.DataMinerObjectModel;
    using Skyline.DataMiner.Net.Messages;

    /// <summary>
    /// Represents a wrapper class for accessing a DomsourceInstance DOM instance.
    /// The <see cref="DomsourceInstance"/> class provides simplified access to the data and functionality of the underlying DOM instance, allowing for easier manipulation and retrieval of data from DOM.
    /// </summary>
    public partial class DomsourceInstance : DomInstanceBase
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DomsourceInstance"/> class. Creates an empty <see cref="DomsourceInstance"/> instance with default settings.
        /// </summary>
        public DomsourceInstance() : base(SlcDocumenthubIds.Definitions.Domsource)
        {
            InitializeProperties();
            AfterLoad();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DomsourceInstance"/> class. Creates an empty <see cref="DomsourceInstance"/> instance with default settings and a specific ID.
        /// </summary>
        public DomsourceInstance(Guid id) : base(SlcDocumenthubIds.Definitions.Domsource, id)
        {
            InitializeProperties();
            AfterLoad();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DomsourceInstance"/> class using the specified <paramref name="domInstance"/> for initializing the object.
        /// </summary>
        /// <param name="domInstance">The <see cref="DomInstance"/> object that provides data for initializing the <see cref="DomsourceInstance"/>. If the section is <c>null</c>, the constructor will not perform any initialization.</param>
        public DomsourceInstance(DomInstance domInstance) : base(domInstance)
        {
            if (!domInstance.DomDefinitionId.Equals(SlcDocumenthubIds.Definitions.Domsource))
                throw new ArgumentException($"The given domInstance, is not of type '{nameof(SlcDocumenthubIds.Definitions.Domsource)}'", nameof(domInstance));
            InitializeProperties();
            AfterLoad();
        }

        /// <summary>
        /// Gets or sets the DOMSourceInfo section of the DOM Instance.
        /// </summary>
        public DOMSourceInfoSection DOMSourceInfo { get; set; }

        public static explicit operator DomsourceInstance(DomInstance instance)
        {
            return new DomsourceInstance(instance);
        }

        /// <summary>
        /// Creates a deep copy of the current <see cref="DomsourceInstance"/>.
        /// </summary>
        /// <returns>A new <see cref="DomsourceInstance"/> object that is a deep copy of this instance.</returns>
        public DomsourceInstance Clone()
        {
            return new DomsourceInstance((DomInstance)this.ToInstance().Clone());
        }

        /// <summary>
        /// Creates a duplicate of the current <see cref="DomsourceInstance"/> with a new id.
        /// </summary>
        /// <returns>A new <see cref="DomsourceInstance"/> object that is a copy of this instance but with a different id.</returns>
        public DomsourceInstance Duplicate()
        {
            var instance = (DomInstance)this.ToInstance().Clone();
            instance.ID = new DomInstanceId(Guid.NewGuid())
            { ModuleId = ModuleId };
            foreach (var section in instance.Sections)
            {
                section.ID = new Skyline.DataMiner.Net.Sections.SectionID(Guid.NewGuid());
            }

            return new DomsourceInstance(instance);
        }

        /// <inheritdoc />
        protected sealed override DomInstance InternalToInstance()
        {
            domInstance.Sections.Clear();
            domInstance.Sections.Add(DOMSourceInfo.ToSection());
            return domInstance;
        }

        /// <inheritdoc />
        public sealed override void Save(DomHelper helper)
        {
            var exist = helper.DomInstances.Read(DomInstanceExposers.Id.Equal(domInstance.ID)).FirstOrDefault();
            var instance = ToInstance();
            if (exist == null)
            {
                domInstance = helper.DomInstances.Create(instance);
            }
            else
            {
                domInstance = helper.DomInstances.Update(instance);
            }
        }

        protected sealed override void InitializeProperties()
        {
            var _dOMSourceInfo = domInstance.Sections.FirstOrDefault(section => section.SectionDefinitionID.Equals(SlcDocumenthubIds.Sections.DOMSourceInfo.Id));
            if (_dOMSourceInfo is null)
            {
                DOMSourceInfo = new DOMSourceInfoSection();
            }
            else
            {
                DOMSourceInfo = new DOMSourceInfoSection(_dOMSourceInfo);
            }
        }
    }
}