//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Dom Code Generator automation script.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace DomHelpers.SlcDocumenthub
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using Skyline.DataMiner.Net.Apps.DataMinerObjectModel;
    using Skyline.DataMiner.Net.Messages;
    using Skyline.DataMiner.Utils.DocumentHub.API.DataHelpers;

    /// <summary>
    /// Represents a wrapper class for accessing a SharepointInstance DOM instance.
    /// The <see cref="SharepointInstance"/> class provides simplified access to the data and functionality of the underlying DOM instance, allowing for easier manipulation and retrieval of data from DOM.
    /// </summary>
    public partial class SharepointInstance : DomInstanceBase
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SharepointInstance"/> class. Creates an empty <see cref="SharepointInstance"/> instance with default settings.
        /// </summary>
        public SharepointInstance() : base(SlcDocumenthubIds.Definitions.Sharepoint)
        {
            InitializeProperties();
            AfterLoad();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SharepointInstance"/> class. Creates an empty <see cref="SharepointInstance"/> instance with default settings and a specific ID.
        /// </summary>
        public SharepointInstance(Guid id) : base(SlcDocumenthubIds.Definitions.Sharepoint, id)
        {
            InitializeProperties();
            AfterLoad();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SharepointInstance"/> class using the specified <paramref name="domInstance"/> for initializing the object.
        /// </summary>
        /// <param name="domInstance">The <see cref="DomInstance"/> object that provides data for initializing the <see cref="SharepointInstance"/>. If the section is <c>null</c>, the constructor will not perform any initialization.</param>
        public SharepointInstance(DomInstance domInstance) : base(domInstance)
        {
            if (!domInstance.DomDefinitionId.Equals(SlcDocumenthubIds.Definitions.Sharepoint))
                throw new ArgumentException($"The given domInstance, is not of type '{nameof(SlcDocumenthubIds.Definitions.Sharepoint)}'", nameof(domInstance));
            InitializeProperties();
            AfterLoad();
        }

        /// <summary>
        /// Gets or sets the Configuration section of the DOM Instance.
        /// </summary>
        public ConfigurationSection Configuration { get; set; }

        public static explicit operator SharepointInstance(DomInstance instance)
        {
            return new SharepointInstance(instance);
        }

        /// <summary>
        /// Creates a deep copy of the current <see cref="SharepointInstance"/>.
        /// </summary>
        /// <returns>A new <see cref="SharepointInstance"/> object that is a deep copy of this instance.</returns>
        public SharepointInstance Clone()
        {
            return new SharepointInstance((DomInstance)this.ToInstance().Clone());
        }

        /// <summary>
        /// Creates a duplicate of the current <see cref="SharepointInstance"/> with a new id.
        /// </summary>
        /// <returns>A new <see cref="SharepointInstance"/> object that is a copy of this instance but with a different id.</returns>
        public SharepointInstance Duplicate()
        {
            var instance = (DomInstance)this.ToInstance().Clone();
            instance.ID = new DomInstanceId(Guid.NewGuid())
            { ModuleId = ModuleId };
            foreach (var section in instance.Sections)
            {
                section.ID = new Skyline.DataMiner.Net.Sections.SectionID(Guid.NewGuid());
            }

            return new SharepointInstance(instance);
        }

        /// <inheritdoc />
        protected sealed override DomInstance InternalToInstance()
        {
            domInstance.Sections.Clear();
            domInstance.Sections.Add(Configuration.ToSection());
            return domInstance;
        }

        /// <inheritdoc />
        public sealed override void Save(DomHelper helper)
        {
            var exist = helper.DomInstances.Read(DomInstanceExposers.Id.Equal(domInstance.ID)).FirstOrDefault();
            var instance = ToInstance();
            if (exist == null)
            {
                domInstance = helper.DomInstances.Create(instance);
            }
            else
            {
                domInstance = helper.DomInstances.Update(instance);
            }
        }

        protected sealed override void InitializeProperties()
        {
            var _configuration = domInstance.Sections.FirstOrDefault(section => section.SectionDefinitionID.Equals(SlcDocumenthubIds.Sections.Configuration.Id));
            if (_configuration is null)
            {
                Configuration = new ConfigurationSection();
            }
            else
            {
                Configuration = new ConfigurationSection(_configuration);
            }
        }
    }
}