//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Skyline.DataMiner.SDM.CodeGenerator package.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Skyline.DataMiner.Solutions.DocumentHub.SDM.Exposers
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using System.Runtime.CompilerServices;
    using Skyline.DataMiner.Net.Messages.SLDataGateway;
    using Skyline.DataMiner.SDM;
    using Skyline.DataMiner.SDM.Exposers;
    using SLDataGateway.API.Querying;
    using SLDataGateway.API.Types.Querying;

    public static partial class DocumentBucketExposers
    {
        public static readonly Exposer<Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.DocumentBucket, string> Identifier = new Exposer<Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.DocumentBucket, string>((obj) => obj.Identifier, "Identifier");
        public static readonly Exposer<Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.DocumentBucket, string> Name = new Exposer<Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.DocumentBucket, string>((obj) => obj.Name, "Name");
        public static readonly Exposer<Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.DocumentBucket, string> Description = new Exposer<Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.DocumentBucket, string>((obj) => obj.Description, "Description");
        public static readonly Exposer<Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.DocumentBucket, string> UploadPath = new Exposer<Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.DocumentBucket, string>((obj) => obj.UploadPath, "UploadPath");
        public static readonly Exposer<Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.DocumentBucket, Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.StorageType> StorageType = new Exposer<Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.DocumentBucket, Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.StorageType>((obj) => obj.StorageType, "StorageType");
        public static readonly Exposer<Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.DocumentBucket, string> Extensions = new Exposer<Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.DocumentBucket, string>((obj) => obj.Extensions, "Extensions");
        public static readonly Exposer<Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.DocumentBucket, bool> IsDefault = new Exposer<Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.DocumentBucket, bool>((obj) => obj.IsDefault, "IsDefault");
        public static readonly Exposer<Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.DocumentBucket, Skyline.DataMiner.SDM.SdmObjectReference<Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.DomSource>> DOMSource = new Exposer<Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.DocumentBucket, Skyline.DataMiner.SDM.SdmObjectReference<Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.DomSource>>((obj) => obj.DOMSource, "DOMSource");
        public static readonly Exposer<Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.DocumentBucket, string> Definition = new Exposer<Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.DocumentBucket, string>((obj) => obj.Definition, "Definition");
        public static readonly Exposer<Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.DocumentBucket, long> SizeLimit = new Exposer<Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.DocumentBucket, long>((obj) => obj.SizeLimit, "SizeLimit");
    }
}