//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the DOM Code Generator automation script.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace DomHelpers.SlcDocumenthub
{
    using System;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Linq;
    using Skyline.DataMiner.Net.Apps.DataMinerObjectModel;
    using Skyline.DataMiner.Net.Apps.Sections.Sections;
    using Skyline.DataMiner.Net.Messages;
    using Skyline.DataMiner.Net.Sections;
    using Skyline.DataMiner.Utils.DocumentHub.API.DataHelpers;

    /// <summary>
    /// Represents a wrapper class for accessing a ConfigurationSection section.
    /// The <see cref="ConfigurationSection"/> class provides simplified access to the data and functionality of the underlying DOM section, allowing for easier manipulation and retrieval of data from DOM.
    /// </summary>
    public partial class ConfigurationSection : DomSectionBase
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ConfigurationSection"/> class. Creates an empty <see cref="ConfigurationSection"/> object with default settings.
        /// </summary>
        public ConfigurationSection() : base(SlcDocumenthubIds.Sections.Configuration.Id)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ConfigurationSection"/> class using the specified <paramref name="section"/> for initializing the object.
        /// </summary>
        /// <param name="section">The <see cref="Section"/> object that provides data for initializing the <see cref="ConfigurationSection"/>. If the section is <c>null</c>, the constructor will not perform any initialization.</param>
        public ConfigurationSection(Section section) : base(section, SlcDocumenthubIds.Sections.Configuration.Id)
        {
        }

        /// <summary>
        /// Gets or sets the ClientID field of the DOM Instance.
        /// </summary>
        /// <remarks>
        /// When retrieving the value:
        /// <list type="bullet">
        /// <item>If the field has been set, it will return the value.</item>
        /// <item>If the field is not set it will return <see langword="null"/>.</item>
        /// </list>
        /// When setting the value:
        /// <list type="bullet">
        /// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
        /// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
        /// </list>
        /// </remarks>
        public String ClientID
        {
            get
            {
                var wrapper = section.GetValue<String>(SlcDocumenthubIds.Sections.Configuration.ClientID);
                if (wrapper != null)
                {
                    return (String)wrapper.Value;
                }
                else
                {
                    return null;
                }
            }

            set
            {
                if (value == null)
                {
                    section.RemoveFieldValueById(SlcDocumenthubIds.Sections.Configuration.ClientID);
                }
                else
                {
                    section.AddOrUpdateValue(SlcDocumenthubIds.Sections.Configuration.ClientID, (String)value);
                }
            }
        }

        /// <summary>
        /// Gets or sets the SiteURL field of the DOM Instance.
        /// </summary>
        /// <remarks>
        /// When retrieving the value:
        /// <list type="bullet">
        /// <item>If the field has been set, it will return the value.</item>
        /// <item>If the field is not set it will return <see langword="null"/>.</item>
        /// </list>
        /// When setting the value:
        /// <list type="bullet">
        /// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
        /// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
        /// </list>
        /// </remarks>
        public String SiteURL
        {
            get
            {
                var wrapper = section.GetValue<String>(SlcDocumenthubIds.Sections.Configuration.SiteURL);
                if (wrapper != null)
                {
                    return (String)wrapper.Value;
                }
                else
                {
                    return null;
                }
            }

            set
            {
                if (value == null)
                {
                    section.RemoveFieldValueById(SlcDocumenthubIds.Sections.Configuration.SiteURL);
                }
                else
                {
                    section.AddOrUpdateValue(SlcDocumenthubIds.Sections.Configuration.SiteURL, (String)value);
                }
            }
        }

        /// <summary>
        /// Gets or sets the ClientSecret field of the DOM Instance.
        /// </summary>
        /// <remarks>
        /// When retrieving the value:
        /// <list type="bullet">
        /// <item>If the field has been set, it will return the value.</item>
        /// <item>If the field is not set it will return <see langword="null"/>.</item>
        /// </list>
        /// When setting the value:
        /// <list type="bullet">
        /// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
        /// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
        /// </list>
        /// </remarks>
        public String ClientSecret
        {
            get
            {
                var wrapper = section.GetValue<String>(SlcDocumenthubIds.Sections.Configuration.ClientSecret);
                if (wrapper != null)
                {
                    return (String)wrapper.Value;
                }
                else
                {
                    return null;
                }
            }

            set
            {
                if (value == null)
                {
                    section.RemoveFieldValueById(SlcDocumenthubIds.Sections.Configuration.ClientSecret);
                }
                else
                {
                    section.AddOrUpdateValue(SlcDocumenthubIds.Sections.Configuration.ClientSecret, (String)value);
                }
            }
        }

        /// <summary>
        /// Gets or sets the DocumentLibraryName field of the DOM Instance.
        /// </summary>
        /// <remarks>
        /// When retrieving the value:
        /// <list type="bullet">
        /// <item>If the field has been set, it will return the value.</item>
        /// <item>If the field is not set it will return <see langword="null"/>.</item>
        /// </list>
        /// When setting the value:
        /// <list type="bullet">
        /// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
        /// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
        /// </list>
        /// </remarks>
        public String DocumentLibraryName
        {
            get
            {
                var wrapper = section.GetValue<String>(SlcDocumenthubIds.Sections.Configuration.DocumentLibraryName);
                if (wrapper != null)
                {
                    return (String)wrapper.Value;
                }
                else
                {
                    return null;
                }
            }

            set
            {
                if (value == null)
                {
                    section.RemoveFieldValueById(SlcDocumenthubIds.Sections.Configuration.DocumentLibraryName);
                }
                else
                {
                    section.AddOrUpdateValue(SlcDocumenthubIds.Sections.Configuration.DocumentLibraryName, (String)value);
                }
            }
        }

        /// <summary>
        /// Gets or sets the Status field of the DOM Instance.
        /// </summary>
        /// <remarks>
        /// When retrieving the value:
        /// <list type="bullet">
        /// <item>If the field has been set, it will return the value.</item>
        /// <item>If the field is not set it will return <see langword="null"/>.</item>
        /// </list>
        /// When setting the value:
        /// <list type="bullet">
        /// <item>If <see langword="null"/> is assigned, the field will be removed from the section.</item>
        /// <item>If a valid value is assigned, the field value will be added or updated in the section.</item>
        /// </list>
        /// </remarks>
        public SlcDocumenthubIds.Enums.Status? Status
        {
            get
            {
                var wrapper = section.GetValue<Int32>(SlcDocumenthubIds.Sections.Configuration.Status);
                if (wrapper != null)
                {
                    return (SlcDocumenthubIds.Enums.Status?)wrapper.Value;
                }
                else
                {
                    return null;
                }
            }

            set
            {
                if (value == null)
                {
                    section.RemoveFieldValueById(SlcDocumenthubIds.Sections.Configuration.Status);
                }
                else
                {
                    section.AddOrUpdateValue(SlcDocumenthubIds.Sections.Configuration.Status, (Int32)value);
                }
            }
        }

        /// <summary>
        /// Gets or sets the TenantID field of the DOM Instance.
        /// </summary>
        /// <remarks>
        /// When retrieving the value:
        /// <list type="bullet">
        /// <item>If the field has been set, it will return the value.</item>
        /// <item>If the field is not set it will return <see langword="null"/>.</item>
        /// </list>
        /// When setting the value:
        /// <list type="bullet">
        /// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
        /// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
        /// </list>
        /// </remarks>
        public String TenantID
        {
            get
            {
                var wrapper = section.GetValue<String>(SlcDocumenthubIds.Sections.Configuration.TenantID);
                if (wrapper != null)
                {
                    return (String)wrapper.Value;
                }
                else
                {
                    return null;
                }
            }

            set
            {
                if (value == null)
                {
                    section.RemoveFieldValueById(SlcDocumenthubIds.Sections.Configuration.TenantID);
                }
                else
                {
                    section.AddOrUpdateValue(SlcDocumenthubIds.Sections.Configuration.TenantID, (String)value);
                }
            }
        }

        /// <summary>
        /// Creates a deep copy of the current <see cref="ConfigurationSection"/>.
        /// </summary>
        /// <returns>A new <see cref="ConfigurationSection"/> object that is a deep copy of this section.</returns>
        public ConfigurationSection Clone()
        {
            return new ConfigurationSection((Section)this.ToSection().Clone());
        }

        /// <summary>
        /// Creates a duplicate of the current <see cref="ConfigurationSection"/> with a new id.
        /// </summary>
        /// <returns>A new <see cref="ConfigurationSection"/> object that is a copy of this section but with a different id.</returns>
        public ConfigurationSection Duplicate()
        {
            var section = (Section)this.ToSection().Clone();
            section.ID = new SectionID(Guid.NewGuid());
            return new ConfigurationSection(section);
        }
    }
}