//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the DOM Code Generator automation script.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace DomHelpers.SlcDocumenthub
{
    using System;
    using Skyline.DataMiner.Net.Apps.DataMinerObjectModel;
    using Skyline.DataMiner.Net.Sections;
    using Skyline.DataMiner.Utils.DocumentHub.API.DataHelpers;

    /// <summary>
    /// Represents a wrapper class for accessing a DOMSourceInfoSection section.
    /// The <see cref="DOMSourceInfoSection"/> class provides simplified access to the data and functionality of the underlying DOM section, allowing for easier manipulation and retrieval of data from DOM.
    /// </summary>
    public partial class DOMSourceInfoSection : DomSectionBase
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DOMSourceInfoSection"/> class. Creates an empty <see cref="DOMSourceInfoSection"/> object with default settings.
        /// </summary>
        public DOMSourceInfoSection() : base(SlcDocumenthubIds.Sections.DOMSourceInfo.Id)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DOMSourceInfoSection"/> class using the specified <paramref name="section"/> for initializing the object.
        /// </summary>
        /// <param name="section">The <see cref="Section"/> object that provides data for initializing the <see cref="DOMSourceInfoSection"/>. If the section is <c>null</c>, the constructor will not perform any initialization.</param>
        public DOMSourceInfoSection(Section section) : base(section, SlcDocumenthubIds.Sections.DOMSourceInfo.Id)
        {
        }

        /// <summary>
        /// Gets or sets the Name field of the DOM Instance.
        /// </summary>
        /// <remarks>
        /// When retrieving the value:
        /// <list type="bullet">
        /// <item>If the field has been set, it will return the value.</item>
        /// <item>If the field is not set it will return <see langword="null"/>.</item>
        /// </list>
        /// When setting the value:
        /// <list type="bullet">
        /// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
        /// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
        /// </list>
        /// </remarks>
        public String Name
        {
            get
            {
                var wrapper = section.GetValue<String>(SlcDocumenthubIds.Sections.DOMSourceInfo.Name);
                if (wrapper != null)
                {
                    return (String)wrapper.Value;
                }
                else
                {
                    return null;
                }
            }

            set
            {
                if (value == null)
                {
                    section.RemoveFieldValueById(SlcDocumenthubIds.Sections.DOMSourceInfo.Name);
                }
                else
                {
                    section.AddOrUpdateValue(SlcDocumenthubIds.Sections.DOMSourceInfo.Name, (String)value);
                }
            }
        }

        /// <summary>
        /// Gets or sets the Module field of the DOM Instance.
        /// </summary>
        /// <remarks>
        /// When retrieving the value:
        /// <list type="bullet">
        /// <item>If the field has been set, it will return the value.</item>
        /// <item>If the field is not set it will return <see langword="null"/>.</item>
        /// </list>
        /// When setting the value:
        /// <list type="bullet">
        /// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
        /// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
        /// </list>
        /// </remarks>
        public String Module
        {
            get
            {
                var wrapper = section.GetValue<String>(SlcDocumenthubIds.Sections.DOMSourceInfo.Module);
                if (wrapper != null)
                {
                    return (String)wrapper.Value;
                }
                else
                {
                    return null;
                }
            }

            set
            {
                if (value == null)
                {
                    section.RemoveFieldValueById(SlcDocumenthubIds.Sections.DOMSourceInfo.Module);
                }
                else
                {
                    section.AddOrUpdateValue(SlcDocumenthubIds.Sections.DOMSourceInfo.Module, (String)value);
                }
            }
        }

        /// <summary>
        /// Gets or sets the NetworkSharePath field of the DOM Instance.
        /// </summary>
        /// <remarks>
        /// When retrieving the value:
        /// <list type="bullet">
        /// <item>If the field has been set, it will return the value.</item>
        /// <item>If the field is not set it will return <see langword="null"/>.</item>
        /// </list>
        /// When setting the value:
        /// <list type="bullet">
        /// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
        /// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
        /// </list>
        /// </remarks>
        public String NetworkSharePath
        {
            get
            {
                var wrapper = section.GetValue<String>(SlcDocumenthubIds.Sections.DOMSourceInfo.NetworkSharePath);
                if (wrapper != null)
                {
                    return (String)wrapper.Value;
                }
                else
                {
                    return null;
                }
            }

            set
            {
                if (value == null)
                {
                    section.RemoveFieldValueById(SlcDocumenthubIds.Sections.DOMSourceInfo.NetworkSharePath);
                }
                else
                {
                    section.AddOrUpdateValue(SlcDocumenthubIds.Sections.DOMSourceInfo.NetworkSharePath, (String)value);
                }
            }
        }

        /// <summary>
        /// Gets or sets the Credential field of the DOM Instance.
        /// </summary>
        /// <remarks>
        /// When retrieving the value:
        /// <list type="bullet">
        /// <item>If the field has been set, it will return the value.</item>
        /// <item>If the field is not set it will return <see langword="null"/>.</item>
        /// </list>
        /// When setting the value:
        /// <list type="bullet">
        /// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
        /// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
        /// </list>
        /// </remarks>
        public String Credential
        {
            get
            {
                var wrapper = section.GetValue<String>(SlcDocumenthubIds.Sections.DOMSourceInfo.Credential);
                if (wrapper != null)
                {
                    return (String)wrapper.Value;
                }
                else
                {
                    return null;
                }
            }

            set
            {
                if (value == null)
                {
                    section.RemoveFieldValueById(SlcDocumenthubIds.Sections.DOMSourceInfo.Credential);
                }
                else
                {
                    section.AddOrUpdateValue(SlcDocumenthubIds.Sections.DOMSourceInfo.Credential, (String)value);
                }
            }
        }

        /// <summary>
        /// Creates a deep copy of the current <see cref="DOMSourceInfoSection"/>.
        /// </summary>
        /// <returns>A new <see cref="DOMSourceInfoSection"/> object that is a deep copy of this section.</returns>
        public DOMSourceInfoSection Clone()
        {
            return new DOMSourceInfoSection((Section)this.ToSection().Clone());
        }

        /// <summary>
        /// Creates a duplicate of the current <see cref="DOMSourceInfoSection"/> with a new id.
        /// </summary>
        /// <returns>A new <see cref="DOMSourceInfoSection"/> object that is a copy of this section but with a different id.</returns>
        public DOMSourceInfoSection Duplicate()
        {
            var section = (Section)this.ToSection().Clone();
            section.ID = new SectionID(Guid.NewGuid());
            return new DOMSourceInfoSection(section);
        }

        /// <inheritdoc />
        protected override Section InternalToSection()
        {
            if (section.GetValue<String>(SlcDocumenthubIds.Sections.DOMSourceInfo.Name) == null)
                throw new InvalidOperationException("'Name' is required. Please fill it in before saving, or mark it as optional with the DOM Editor.");
            if (section.GetValue<String>(SlcDocumenthubIds.Sections.DOMSourceInfo.Module) == null)
                throw new InvalidOperationException("'Module' is required. Please fill it in before saving, or mark it as optional with the DOM Editor.");
            if (section.GetValue<String>(SlcDocumenthubIds.Sections.DOMSourceInfo.NetworkSharePath) == null)
                throw new InvalidOperationException("'NetworkSharePath' is required. Please fill it in before saving, or mark it as optional with the DOM Editor.");
            if (section.GetValue<String>(SlcDocumenthubIds.Sections.DOMSourceInfo.Credential) == null)
                throw new InvalidOperationException("'Credential' is required. Please fill it in before saving, or mark it as optional with the DOM Editor.");
            return section;
        }
    }
}