//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the DOM Code Generator automation script.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace DomHelpers
{
    using System;
    using System.Linq;
    using Skyline.DataMiner.Net.Apps.DataMinerObjectModel;
    using Skyline.DataMiner.Net.Sections;

    public abstract class DomSectionBase : IEquatable<DomSectionBase>
    {
        protected Section section;
        protected DomSectionBase(SectionDefinitionID id)
        {
            if (id == null)
                throw new ArgumentNullException("id");
            this.section = new Section(id);
            AfterLoad();
        }

        protected DomSectionBase(SectionDefinition definition)
        {
            if (definition == null)
                throw new ArgumentNullException("definition");
            this.section = new Section(definition);
            AfterLoad();
        }

        protected DomSectionBase(Section section, SectionDefinitionID id)
        {
            if (section == null)
                throw new ArgumentNullException("section");
            if (section.SectionDefinitionID == null)
            {
                throw new ArgumentException("The given section doesn't have a valid SectionDefinitionId.", nameof(section));
            }

            if (!section.SectionDefinitionID.Equals(id))
            {
                throw new ArgumentException($"The given section, is not of type '{nameof(id)}'", nameof(section));
            }

            this.section = section;
            AfterLoad();
        }

        /// <summary>
        /// Gets the section's ID.
        /// </summary>
        public SectionID ID
        {
            get
            {
                return section.ID;
            }
        }

        /// <summary>
        /// Gets the section's Section Definition ID.
        /// </summary>
        public SectionDefinitionID SectionDefinitionID
        {
            get
            {
                return section.SectionDefinitionID;
            }
        }

        /// <summary>
        /// Gets a value indicating whether the section is empty.
        /// </summary>
        /// <value>
        /// <see langword="true"/> if the section doesn't contains any field values, otherwise, <see langword="false"/>.
        /// </value>
        public bool IsEmpty
        {
            get
            {
                return !section.FieldValues.Any();
            }
        }

        public static implicit operator SectionDefinitionID(DomSectionBase sectionBase)
        {
            return sectionBase.section.SectionDefinitionID;
        }

        public static implicit operator SectionDefinition(DomSectionBase sectionBase)
        {
            return sectionBase.section.GetSectionDefinition();
        }

        public static bool operator ==(DomSectionBase left, DomSectionBase right)
        {
            if (left is null)
            {
                return right is null;
            }

            return left.Equals(right);
        }

        public static bool operator !=(DomSectionBase left, DomSectionBase right)
        {
            return !(left == right);
        }

        public override string ToString()
        {
            return $"{this.section.SectionDefinitionID}";
        }

        /// <summary>
        /// Optional method that runs at the end of the constructor.
        /// </summary>
        protected virtual void AfterLoad()
        {
        }

        public virtual Section ToSection()
        {
            BeforeToSection();
            var section = InternalToSection();
            AfterToSection();
            return section;
        }

        /// <summary>
        /// Optional method that runs before the internal ToSection method runs.
        /// </summary>
        protected virtual void BeforeToSection()
        {
        }

        protected virtual Section InternalToSection()
        {
            return this.section;
        }

        /// <summary>
        /// Optional method that runs after the internal ToSection method runs.
        /// </summary>
        protected virtual void AfterToSection()
        {
        }

        public override int GetHashCode()
        {
            return this.ID.GetHashCode();
        }

        public override bool Equals(object obj)
        {
            return Equals(obj as DomSectionBase);
        }

        public bool Equals(DomSectionBase other)
        {
            if (other is null)
            {
                return false;
            }

            if (ReferenceEquals(this, other))
            {
                return true;
            }

            return this.ID.Equals(other.ID);
        }
    }
}