#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Dom Editor automation script.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Skyline.DataMiner.Utils.DocumentHub.API.DataHelpers
{
    using System;
    using System.ComponentModel;
    using Skyline.DataMiner.Net.Apps.DataMinerObjectModel;
    using Skyline.DataMiner.Net.Sections;
    using Skyline.DataMiner.SDM;

    public static class SlcDocumenthubIds
    {
        public const string ModuleId = "(slc)documenthub";
        public static class Enums
        {
            public enum Storagetype
            {
                Local = 0,
                Sharepoint = 1,
                DOM = 2
            }

            public enum Status
            {
                Disconnected = 0,
                Connected = 1
            }
        }

        public static class Sections
        {
            public static class DOMSourceInfo
            {
                public static SectionDefinitionID Id { get; } = new SectionDefinitionID(new Guid("a98e6176-ce32-45d1-a8f8-e1baea6d4488"))
                { ModuleId = ModuleId };
                public static FieldDescriptorID Name { get; } = new FieldDescriptorID(new Guid("fdf73d52-590c-4b67-8d92-a367651790eb"));
                public static FieldDescriptorID Module { get; } = new FieldDescriptorID(new Guid("98bdd53d-deda-497a-8394-2f503d294015"));
                public static FieldDescriptorID NetworkSharePath { get; } = new FieldDescriptorID(new Guid("2ccfdd77-f0a5-4607-8a52-afba8c3bef82"));
                public static FieldDescriptorID Credential { get; } = new FieldDescriptorID(new Guid("ec214b80-298c-421f-b352-c2a3d5200de9"));
            }

            public static class CategoryInfo
            {
                public static SectionDefinitionID Id { get; } = new SectionDefinitionID(new Guid("9dee7951-0ce8-42d1-8601-f1eb8c28a12c"))
                { ModuleId = ModuleId };
                public static FieldDescriptorID Name { get; } = new FieldDescriptorID(new Guid("d86b22d3-b231-4bc0-8c70-d38c50fd10d8"));
                public static FieldDescriptorID Uploadpath { get; } = new FieldDescriptorID(new Guid("a45f2ac8-a6e4-4650-afe2-a6ea7f4262b8"));
                public static FieldDescriptorID Description { get; } = new FieldDescriptorID(new Guid("dc4c9953-9bdf-421f-9a0f-384ca4eace07"));
                public static FieldDescriptorID Storagetype { get; } = new FieldDescriptorID(new Guid("36c92e1d-0108-4e6d-a411-189ecd9869ea"));
                public static FieldDescriptorID Extensions { get; } = new FieldDescriptorID(new Guid("9a62750a-de42-4241-b937-54ea4b79ca90"));
                public static FieldDescriptorID Isdefault { get; } = new FieldDescriptorID(new Guid("f0b2c67c-34f5-4aea-b869-68c134a7bdd8"));
                public static FieldDescriptorID Definition { get; } = new FieldDescriptorID(new Guid("239b1596-a92c-4552-8086-701270068fbf"));
                public static FieldDescriptorID Domsource { get; } = new FieldDescriptorID(new Guid("375d860c-9b5d-424b-a1bf-88ceb3a9a280"));
            }

            public static class Configuration
            {
                public static SectionDefinitionID Id { get; } = new SectionDefinitionID(new Guid("2b038372-b61c-43d4-a39d-325e058a62fc"))
                { ModuleId = ModuleId };
                public static FieldDescriptorID ClientID { get; } = new FieldDescriptorID(new Guid("2b9b4f74-7863-49cc-bef8-7bbc102d9f64"));
                public static FieldDescriptorID SiteURL { get; } = new FieldDescriptorID(new Guid("b4da0186-d6a7-4958-b949-ea5776e9e1c6"));
                public static FieldDescriptorID ClientSecret { get; } = new FieldDescriptorID(new Guid("c41be706-8539-46ab-b886-14e89db9403e"));
                public static FieldDescriptorID DocumentLibraryName { get; } = new FieldDescriptorID(new Guid("d335800d-f136-4fae-a9ea-0df843394d89"));
                public static FieldDescriptorID Status { get; } = new FieldDescriptorID(new Guid("e1d9468d-69b7-4b51-856d-70c30ffb74a0"));
                public static FieldDescriptorID TenantID { get; } = new FieldDescriptorID(new Guid("f14e860b-7d10-46db-aae9-82817d2e2862"));
            }
        }

        public static class Definitions
        {
            public static DomDefinitionId Domsource { get; } = new DomDefinitionId(new Guid("5ec0807d-7e0f-4fc2-9e60-53db664614f7"))
            { ModuleId = ModuleId };
            public static DomDefinitionId Sharepoint { get; } = new DomDefinitionId(new Guid("f0492169-2e70-4aa3-a06a-28e8091b785a"))
            { ModuleId = ModuleId };
            public static DomDefinitionId DocumentCategory { get; } = new DomDefinitionId(new Guid("c5a9829c-5ca1-4a29-87d0-88e4e4d13ace"))
            { ModuleId = ModuleId };
        }

        public static class Behaviors
        {
        }
    }
}
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member