<Project Sdk="Skyline.DataMiner.Sdk">
	<PropertyGroup>
		<TargetFramework>net48</TargetFramework>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
	</PropertyGroup>
	<PropertyGroup>
		<DataMinerType>Package</DataMinerType>
		<GenerateDataMinerPackage>True</GenerateDataMinerPackage>
		<MinimumRequiredDmVersion>10.4.0.0 - 14003</MinimumRequiredDmVersion>
		<!-- <MinimumRequiredDmWebVersion>10.6.2 (CU0)</MinimumRequiredDmWebVersion> -->
		<PackageVersion>1.1.1-alpha22</PackageVersion>
		<Version>1.0.0</Version>
		<VersionComment>Initial Version</VersionComment>
		<!-- Do NOT fill in the Organization Token here. This points to either an Environment Variable skyline__sdk__dataminertoken holding the organization token or a Visual Studio User Secret holding the token. -->
		<CatalogPublishKeyName>skyline:sdk:dataminertoken</CatalogPublishKeyName>
		<CatalogDefaultDownloadKeyName>skyline:sdk:dataminertoken</CatalogDefaultDownloadKeyName>
		<AssemblyTitle>Skyline.DataMiner.Solutions.DocumentHub.Installer</AssemblyTitle>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Skyline.DataMiner.CICD.CSharpAnalysis.Analyzer" Version="2.1.2">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Skyline.DataMiner.Core.AppPackageInstaller" Version="4.0.0" />
		<PackageReference Include="Skyline.DataMiner.Dev.Automation" Version="10.6.3.1" />
		<PackageReference Include="Skyline.DataMiner.Dev.Utils.SDM.Abstractions" Version="1.0.1" />
		<PackageReference Include="Skyline.DataMiner.SDM" Version="1.0.1" />
		<PackageReference Include="Skyline.DataMiner.Utils.DOM" Version="10.5.2.6" />
		<PackageReference Include="Skyline.DataMiner.Utils.SecureCoding.Analyzers" Version="2.2.3">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>
	<Import Project="..\SharedMappers\SharedMappers.projitems" Label="Shared" />
</Project>