//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the DOM Code Generator automation script.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace DomHelpers
{
	using System;
	using System.Linq;
	using Skyline.DataMiner.Net.Apps.DataMinerObjectModel;
	using Skyline.DataMiner.Net.ManagerStore;
	using Skyline.DataMiner.Net.Messages;
	using Skyline.DataMiner.Net.Sections;

	/// <summary>
	/// Serves as the abstract base class for wrapper classes that provide access to DOM instances.
	/// The <see cref="DomInstanceBase"/> class defines the common functionality and structure for interacting with DOM objects stored in the database, serving as a foundation for derived classes that wrap specific DOM instances.
	/// </summary>
	public abstract class DomInstanceBase : IEquatable<DomInstanceBase>
	{
		protected DomInstanceBase(DomDefinitionId definitionId)
		{
			if (definitionId == null)
				throw new ArgumentNullException("definitionId");
			domInstance = new DomInstance { DomDefinitionId = definitionId };
		}

		protected DomInstanceBase(DomDefinitionId definitionId, Guid id)
		{
			if (definitionId == null)
				throw new ArgumentNullException("definitionId");
			if (id == Guid.Empty)
				throw new ArgumentException("The id cannot be an empty guid", nameof(id));
			domInstance = new DomInstance
			{
				ID = new DomInstanceId(id)
				{ ModuleId = definitionId.ModuleId },
				DomDefinitionId = definitionId
			};
		}

		protected DomInstanceBase(DomInstance domInstance)
		{
			if (domInstance == null)
				throw new ArgumentNullException("domInstance");
			this.domInstance = domInstance;
		}

		/// <summary>
		/// Gets the Module ID of the DOM Instance.
		/// </summary>
		public String ModuleId
		{
			get
			{
				return domInstance.DomDefinitionId.ModuleId;
			}
		}

		/// <summary>
		/// Gets the ID of the DOM Instance.
		/// </summary>
		public DomInstanceId ID
		{
			get
			{
				return domInstance.ID;
			}
		}

		/// <summary>
		/// Gets the name of the DOM Instance.
		/// </summary>
		public String Name
		{
			get
			{
				return domInstance.Name;
			}
		}

		/// <summary>
		/// Gets the Status ID of the DOM Instance.
		/// </summary>
		public String StatusId
		{
			get
			{
				return domInstance.StatusId;
			}
		}

		/// <summary>
		/// Gets the underlying DOM Instance.
		/// </summary>
		public DomDefinitionId DomDefinitionId
		{
			get
			{
				return domInstance.DomDefinitionId;
			}
		}

		protected DomInstance domInstance { get; set; }

		/// <summary>
		/// Gets the datetime when the DOM Instance was created in UTC.
		/// </summary>
		public DateTimeOffset CreatedAt
		{
			get
			{
				return ((ITrackCreatedAt)domInstance).CreatedAt;
			}
		}

		/// <summary>
		/// Gets the user that created the DOM Instance.
		/// </summary>
		public string CreatedBy
		{
			get
			{
				return ((ITrackCreatedBy)domInstance).CreatedBy;
			}
		}

		/// <summary>
		/// Gets the datetime when the DOM Instance was last modified in UTC.
		/// </summary>
		public DateTimeOffset LastModified
		{
			get
			{
				return ((ITrackLastModified)domInstance).LastModified;
			}
		}

		/// <summary>
		/// Gets the user that last modified the DOM Instance.
		/// </summary>
		public string LastModifiedBy
		{
			get
			{
				return ((ITrackLastModifiedBy)domInstance).LastModifiedBy;
			}
		}

		public static implicit operator DomInstanceId(DomInstanceBase instance)
		{
			return instance.ID;
		}

		public static implicit operator DomInstance(DomInstanceBase instance)
		{
			return instance.ToInstance();
		}

		public static bool operator ==(DomInstanceBase left, DomInstanceBase right)
		{
			if (left is null)
			{
				return right is null;
			}

			return left.Equals(right);
		}

		public static bool operator !=(DomInstanceBase left, DomInstanceBase right)
		{
			return !(left == right);
		}

		/// <summary>
		/// Deletes this DOM Instance from the database.
		/// </summary>
		/// <param name="messageHandler">The connection to the DataMiner system.</param>
		public void Delete(Func<DMSMessage[], DMSMessage[]> messageHandler)
		{
			Delete(new DomHelper(messageHandler, ModuleId));
		}

		/// <summary>
		/// Deletes this DOM Instance from the database.
		/// </summary>
		/// <param name="helper">The connection to the DataMiner system.</param>
		public void Delete(DomHelper helper)
		{
			helper.DomInstances.Delete(domInstance);
		}

		/// <summary>
		/// Saves this DOM Instance to the database.
		/// </summary>
		/// <param name="messageHandler">The connection to the DataMiner system.</param>
		public void Save(Func<DMSMessage[], DMSMessage[]> messageHandler)
		{
			Save(new DomHelper(messageHandler, ModuleId));
		}

		/// <summary>
		/// Saves this DOM Instance to the database.
		/// </summary>
		/// <param name="helper">The connection to the DataMiner system.</param>
		public abstract void Save(DomHelper helper);
		/// <summary>
		/// Return the DOM Instance object with all the fields filled in according to this object.
		/// </summary>
		public DomInstance ToInstance()
		{
			BeforeToInstance();
			var instance = InternalToInstance();
			AfterToInstance();
			return instance;
		}

		/// <summary>
		/// Optional method that runs before the internal ToInstance method runs.
		/// </summary>
		protected virtual void BeforeToInstance()
		{
		}

		/// <summary>
		/// Return the DOM Instance object with all the fields filled in according to this object.
		/// </summary>
		protected abstract DomInstance InternalToInstance();
		/// <summary>
		/// Optional method that runs after the internal ToInstance method runs.
		/// </summary>
		protected virtual void AfterToInstance()
		{
		}

		protected abstract void InitializeProperties();
		/// <summary>
		/// Optional method that runs after the object is constructed and the initialize has ran.
		/// </summary>
		protected virtual void AfterLoad()
		{
		}

		public override int GetHashCode()
		{
			return this.ID.GetHashCode();
		}

		public override bool Equals(object obj)
		{
			return Equals(obj as DomInstanceBase);
		}

		public bool Equals(DomInstanceBase other)
		{
			if (other is null)
			{
				return false;
			}

			if (ReferenceEquals(this, other))
			{
				return true;
			}

			return this.ID.Equals(other.ID);
		}
	}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the DOM Code Generator automation script.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace DomHelpers
{
	using System;
	using System.Linq;
	using Skyline.DataMiner.Net.Apps.DataMinerObjectModel;
	using Skyline.DataMiner.Net.Sections;

	public abstract class DomSectionBase : IEquatable<DomSectionBase>
	{
		protected Section section;
		protected DomSectionBase(SectionDefinitionID id)
		{
			if (id == null)
				throw new ArgumentNullException("id");
			this.section = new Section(id);
			AfterLoad();
		}

		protected DomSectionBase(SectionDefinition definition)
		{
			if (definition == null)
				throw new ArgumentNullException("definition");
			this.section = new Section(definition);
			AfterLoad();
		}

		protected DomSectionBase(Section section, SectionDefinitionID id)
		{
			if (section == null)
				throw new ArgumentNullException("section");
			if (section.SectionDefinitionID == null)
			{
				throw new ArgumentException("The given section doesn't have a valid SectionDefinitionId.", nameof(section));
			}

			if (!section.SectionDefinitionID.Equals(id))
			{
				throw new ArgumentException($"The given section, is not of type '{nameof(id)}'", nameof(section));
			}

			this.section = section;
			AfterLoad();
		}

		/// <summary>
		/// Gets the section's ID.
		/// </summary>
		public SectionID ID
		{
			get
			{
				return section.ID;
			}
		}

		/// <summary>
		/// Gets the section's Section Definition ID.
		/// </summary>
		public SectionDefinitionID SectionDefinitionID
		{
			get
			{
				return section.SectionDefinitionID;
			}
		}

		/// <summary>
		/// Gets a value indicating whether the section is empty.
		/// </summary>
		/// <value>
		/// <see langword="true"/> if the section doesn't contains any field values, otherwise, <see langword="false"/>.
		/// </value>
		public bool IsEmpty
		{
			get
			{
				return !section.FieldValues.Any();
			}
		}

		public static implicit operator SectionDefinitionID(DomSectionBase sectionBase)
		{
			return sectionBase.section.SectionDefinitionID;
		}

		public static implicit operator SectionDefinition(DomSectionBase sectionBase)
		{
			return sectionBase.section.GetSectionDefinition();
		}

		public static bool operator ==(DomSectionBase left, DomSectionBase right)
		{
			if (left is null)
			{
				return right is null;
			}

			return left.Equals(right);
		}

		public static bool operator !=(DomSectionBase left, DomSectionBase right)
		{
			return !(left == right);
		}

		public override string ToString()
		{
			return $"{this.section.SectionDefinitionID}";
		}

		/// <summary>
		/// Optional method that runs at the end of the constructor.
		/// </summary>
		protected virtual void AfterLoad()
		{
		}

		public virtual Section ToSection()
		{
			BeforeToSection();
			var section = InternalToSection();
			AfterToSection();
			return section;
		}

		/// <summary>
		/// Optional method that runs before the internal ToSection method runs.
		/// </summary>
		protected virtual void BeforeToSection()
		{
		}

		protected virtual Section InternalToSection()
		{
			return this.section;
		}

		/// <summary>
		/// Optional method that runs after the internal ToSection method runs.
		/// </summary>
		protected virtual void AfterToSection()
		{
		}

		public override int GetHashCode()
		{
			return this.ID.GetHashCode();
		}

		public override bool Equals(object obj)
		{
			return Equals(obj as DomSectionBase);
		}

		public bool Equals(DomSectionBase other)
		{
			if (other is null)
			{
				return false;
			}

			if (ReferenceEquals(this, other))
			{
				return true;
			}

			return this.ID.Equals(other.ID);
		}
	}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Dom Editor automation script.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace DomHelpers.SlcDocumenthub
{
	using System;
	using System.ComponentModel;
	using Skyline.DataMiner.Net.Apps.DataMinerObjectModel;
	using Skyline.DataMiner.Net.Sections;

	public static class SlcDocumenthubIds
	{
		public const string ModuleId = "(slc)documenthub";
		public static class Enums
		{
			public enum Storagetype
			{
				Local = 0,
				Sharepoint = 1,
				DOM = 2
			}

			public enum Status
			{
				Disconnected = 0,
				Connected = 1
			}
		}

		public static class Sections
		{
			public static class DOMSourceInfo
			{
				public static SectionDefinitionID Id { get; } = new SectionDefinitionID(new Guid("a98e6176-ce32-45d1-a8f8-e1baea6d4488"))
				{ ModuleId = "(slc)documenthub" };
				public static FieldDescriptorID Name { get; } = new FieldDescriptorID(new Guid("fdf73d52-590c-4b67-8d92-a367651790eb"));
				public static FieldDescriptorID Module { get; } = new FieldDescriptorID(new Guid("98bdd53d-deda-497a-8394-2f503d294015"));
				public static FieldDescriptorID NetworkSharePath { get; } = new FieldDescriptorID(new Guid("2ccfdd77-f0a5-4607-8a52-afba8c3bef82"));
				public static FieldDescriptorID Credential { get; } = new FieldDescriptorID(new Guid("ec214b80-298c-421f-b352-c2a3d5200de9"));
			}

			public static class CategoryInfo
			{
				public static SectionDefinitionID Id { get; } = new SectionDefinitionID(new Guid("9dee7951-0ce8-42d1-8601-f1eb8c28a12c"))
				{ ModuleId = "(slc)documenthub" };
				public static FieldDescriptorID Name { get; } = new FieldDescriptorID(new Guid("d86b22d3-b231-4bc0-8c70-d38c50fd10d8"));
				public static FieldDescriptorID Uploadpath { get; } = new FieldDescriptorID(new Guid("a45f2ac8-a6e4-4650-afe2-a6ea7f4262b8"));
				public static FieldDescriptorID Description { get; } = new FieldDescriptorID(new Guid("dc4c9953-9bdf-421f-9a0f-384ca4eace07"));
				public static FieldDescriptorID Storagetype { get; } = new FieldDescriptorID(new Guid("36c92e1d-0108-4e6d-a411-189ecd9869ea"));
				public static FieldDescriptorID Extensions { get; } = new FieldDescriptorID(new Guid("9a62750a-de42-4241-b937-54ea4b79ca90"));
				public static FieldDescriptorID Isdefault { get; } = new FieldDescriptorID(new Guid("f0b2c67c-34f5-4aea-b869-68c134a7bdd8"));
				public static FieldDescriptorID Definition { get; } = new FieldDescriptorID(new Guid("239b1596-a92c-4552-8086-701270068fbf"));
				public static FieldDescriptorID Domsource { get; } = new FieldDescriptorID(new Guid("375d860c-9b5d-424b-a1bf-88ceb3a9a280"));
			}

			public static class Configuration
			{
				public static SectionDefinitionID Id { get; } = new SectionDefinitionID(new Guid("2b038372-b61c-43d4-a39d-325e058a62fc"))
				{ ModuleId = "(slc)documenthub" };
				public static FieldDescriptorID ClientID { get; } = new FieldDescriptorID(new Guid("2b9b4f74-7863-49cc-bef8-7bbc102d9f64"));
				public static FieldDescriptorID SiteURL { get; } = new FieldDescriptorID(new Guid("b4da0186-d6a7-4958-b949-ea5776e9e1c6"));
				public static FieldDescriptorID ClientSecret { get; } = new FieldDescriptorID(new Guid("c41be706-8539-46ab-b886-14e89db9403e"));
				public static FieldDescriptorID DocumentLibraryName { get; } = new FieldDescriptorID(new Guid("d335800d-f136-4fae-a9ea-0df843394d89"));
				public static FieldDescriptorID Status { get; } = new FieldDescriptorID(new Guid("e1d9468d-69b7-4b51-856d-70c30ffb74a0"));
				public static FieldDescriptorID TenantID { get; } = new FieldDescriptorID(new Guid("f14e860b-7d10-46db-aae9-82817d2e2862"));
			}
		}

		public static class Definitions
		{
			public static DomDefinitionId Domsource { get; } = new DomDefinitionId(new Guid("5ec0807d-7e0f-4fc2-9e60-53db664614f7"))
			{ ModuleId = "(slc)documenthub" };
			public static DomDefinitionId Sharepoint { get; } = new DomDefinitionId(new Guid("f0492169-2e70-4aa3-a06a-28e8091b785a"))
			{ ModuleId = "(slc)documenthub" };
			public static DomDefinitionId DocumentCategory { get; } = new DomDefinitionId(new Guid("c5a9829c-5ca1-4a29-87d0-88e4e4d13ace"))
			{ ModuleId = "(slc)documenthub" };
		}

		public static class Behaviors
		{
		}
	}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Dom Code Generator automation script.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace DomHelpers.SlcDocumenthub
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using Skyline.DataMiner.Net.Apps.DataMinerObjectModel;
	using Skyline.DataMiner.Net.Messages;

	/// <summary>
	/// Represents a wrapper class for accessing a DomsourceInstance DOM instance.
	/// The <see cref="DomsourceInstance"/> class provides simplified access to the data and functionality of the underlying DOM instance, allowing for easier manipulation and retrieval of data from DOM.
	/// </summary>
	public partial class DomsourceInstance : DomInstanceBase
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="DomsourceInstance"/> class. Creates an empty <see cref="DomsourceInstance"/> instance with default settings.
		/// </summary>
		public DomsourceInstance() : base(SlcDocumenthubIds.Definitions.Domsource)
		{
			InitializeProperties();
			AfterLoad();
		}

		/// <summary>
		/// Initializes a new instance of the <see cref="DomsourceInstance"/> class. Creates an empty <see cref="DomsourceInstance"/> instance with default settings and a specific ID.
		/// </summary>
		public DomsourceInstance(Guid id) : base(SlcDocumenthubIds.Definitions.Domsource, id)
		{
			InitializeProperties();
			AfterLoad();
		}

		/// <summary>
		/// Initializes a new instance of the <see cref="DomsourceInstance"/> class using the specified <paramref name="domInstance"/> for initializing the object.
		/// </summary>
		/// <param name="domInstance">The <see cref="DomInstance"/> object that provides data for initializing the <see cref="DomsourceInstance"/>. If the section is <c>null</c>, the constructor will not perform any initialization.</param>
		public DomsourceInstance(DomInstance domInstance) : base(domInstance)
		{
			if (!domInstance.DomDefinitionId.Equals(SlcDocumenthubIds.Definitions.Domsource))
				throw new ArgumentException($"The given domInstance, is not of type '{nameof(SlcDocumenthubIds.Definitions.Domsource)}'", nameof(domInstance));
			InitializeProperties();
			AfterLoad();
		}

		/// <summary>
		/// Gets or sets the DOMSourceInfo section of the DOM Instance.
		/// </summary>
		public DOMSourceInfoSection DOMSourceInfo { get; set; }

		public static explicit operator DomsourceInstance(DomInstance instance)
		{
			return new DomsourceInstance(instance);
		}

		/// <summary>
		/// Creates a deep copy of the current <see cref="DomsourceInstance"/>.
		/// </summary>
		/// <returns>A new <see cref="DomsourceInstance"/> object that is a deep copy of this instance.</returns>
		public DomsourceInstance Clone()
		{
			return new DomsourceInstance((DomInstance)this.ToInstance().Clone());
		}

		/// <summary>
		/// Creates a duplicate of the current <see cref="DomsourceInstance"/> with a new id.
		/// </summary>
		/// <returns>A new <see cref="DomsourceInstance"/> object that is a copy of this instance but with a different id.</returns>
		public DomsourceInstance Duplicate()
		{
			var instance = (DomInstance)this.ToInstance().Clone();
			instance.ID = new DomInstanceId(Guid.NewGuid())
			{ ModuleId = ModuleId };
			foreach (var section in instance.Sections)
			{
				section.ID = new Skyline.DataMiner.Net.Sections.SectionID(Guid.NewGuid());
			}

			return new DomsourceInstance(instance);
		}

		/// <inheritdoc />
		protected sealed override DomInstance InternalToInstance()
		{
			domInstance.Sections.Clear();
			domInstance.Sections.Add(DOMSourceInfo.ToSection());
			return domInstance;
		}

		/// <inheritdoc />
		public sealed override void Save(DomHelper helper)
		{
			var exist = helper.DomInstances.Read(DomInstanceExposers.Id.Equal(domInstance.ID)).FirstOrDefault();
			var instance = ToInstance();
			if (exist == null)
			{
				domInstance = helper.DomInstances.Create(instance);
			}
			else
			{
				domInstance = helper.DomInstances.Update(instance);
			}
		}

		protected sealed override void InitializeProperties()
		{
			var _dOMSourceInfo = domInstance.Sections.FirstOrDefault(section => section.SectionDefinitionID.Equals(SlcDocumenthubIds.Sections.DOMSourceInfo.Id));
			if (_dOMSourceInfo is null)
			{
				DOMSourceInfo = new DOMSourceInfoSection();
			}
			else
			{
				DOMSourceInfo = new DOMSourceInfoSection(_dOMSourceInfo);
			}
		}
	}

	/// <summary>
	/// Represents a wrapper class for accessing a SharepointInstance DOM instance.
	/// The <see cref="SharepointInstance"/> class provides simplified access to the data and functionality of the underlying DOM instance, allowing for easier manipulation and retrieval of data from DOM.
	/// </summary>
	public partial class SharepointInstance : DomInstanceBase
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="SharepointInstance"/> class. Creates an empty <see cref="SharepointInstance"/> instance with default settings.
		/// </summary>
		public SharepointInstance() : base(SlcDocumenthubIds.Definitions.Sharepoint)
		{
			InitializeProperties();
			AfterLoad();
		}

		/// <summary>
		/// Initializes a new instance of the <see cref="SharepointInstance"/> class. Creates an empty <see cref="SharepointInstance"/> instance with default settings and a specific ID.
		/// </summary>
		public SharepointInstance(Guid id) : base(SlcDocumenthubIds.Definitions.Sharepoint, id)
		{
			InitializeProperties();
			AfterLoad();
		}

		/// <summary>
		/// Initializes a new instance of the <see cref="SharepointInstance"/> class using the specified <paramref name="domInstance"/> for initializing the object.
		/// </summary>
		/// <param name="domInstance">The <see cref="DomInstance"/> object that provides data for initializing the <see cref="SharepointInstance"/>. If the section is <c>null</c>, the constructor will not perform any initialization.</param>
		public SharepointInstance(DomInstance domInstance) : base(domInstance)
		{
			if (!domInstance.DomDefinitionId.Equals(SlcDocumenthubIds.Definitions.Sharepoint))
				throw new ArgumentException($"The given domInstance, is not of type '{nameof(SlcDocumenthubIds.Definitions.Sharepoint)}'", nameof(domInstance));
			InitializeProperties();
			AfterLoad();
		}

		/// <summary>
		/// Gets or sets the Configuration section of the DOM Instance.
		/// </summary>
		public ConfigurationSection Configuration { get; set; }

		public static explicit operator SharepointInstance(DomInstance instance)
		{
			return new SharepointInstance(instance);
		}

		/// <summary>
		/// Creates a deep copy of the current <see cref="SharepointInstance"/>.
		/// </summary>
		/// <returns>A new <see cref="SharepointInstance"/> object that is a deep copy of this instance.</returns>
		public SharepointInstance Clone()
		{
			return new SharepointInstance((DomInstance)this.ToInstance().Clone());
		}

		/// <summary>
		/// Creates a duplicate of the current <see cref="SharepointInstance"/> with a new id.
		/// </summary>
		/// <returns>A new <see cref="SharepointInstance"/> object that is a copy of this instance but with a different id.</returns>
		public SharepointInstance Duplicate()
		{
			var instance = (DomInstance)this.ToInstance().Clone();
			instance.ID = new DomInstanceId(Guid.NewGuid())
			{ ModuleId = ModuleId };
			foreach (var section in instance.Sections)
			{
				section.ID = new Skyline.DataMiner.Net.Sections.SectionID(Guid.NewGuid());
			}

			return new SharepointInstance(instance);
		}

		/// <inheritdoc />
		protected sealed override DomInstance InternalToInstance()
		{
			domInstance.Sections.Clear();
			domInstance.Sections.Add(Configuration.ToSection());
			return domInstance;
		}

		/// <inheritdoc />
		public sealed override void Save(DomHelper helper)
		{
			var exist = helper.DomInstances.Read(DomInstanceExposers.Id.Equal(domInstance.ID)).FirstOrDefault();
			var instance = ToInstance();
			if (exist == null)
			{
				domInstance = helper.DomInstances.Create(instance);
			}
			else
			{
				domInstance = helper.DomInstances.Update(instance);
			}
		}

		protected sealed override void InitializeProperties()
		{
			var _configuration = domInstance.Sections.FirstOrDefault(section => section.SectionDefinitionID.Equals(SlcDocumenthubIds.Sections.Configuration.Id));
			if (_configuration is null)
			{
				Configuration = new ConfigurationSection();
			}
			else
			{
				Configuration = new ConfigurationSection(_configuration);
			}
		}
	}

	/// <summary>
	/// Represents a wrapper class for accessing a DocumentCategoryInstance DOM instance.
	/// The <see cref="DocumentCategoryInstance"/> class provides simplified access to the data and functionality of the underlying DOM instance, allowing for easier manipulation and retrieval of data from DOM.
	/// </summary>
	public partial class DocumentCategoryInstance : DomInstanceBase
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="DocumentCategoryInstance"/> class. Creates an empty <see cref="DocumentCategoryInstance"/> instance with default settings.
		/// </summary>
		public DocumentCategoryInstance() : base(SlcDocumenthubIds.Definitions.DocumentCategory)
		{
			InitializeProperties();
			AfterLoad();
		}

		/// <summary>
		/// Initializes a new instance of the <see cref="DocumentCategoryInstance"/> class. Creates an empty <see cref="DocumentCategoryInstance"/> instance with default settings and a specific ID.
		/// </summary>
		public DocumentCategoryInstance(Guid id) : base(SlcDocumenthubIds.Definitions.DocumentCategory, id)
		{
			InitializeProperties();
			AfterLoad();
		}

		/// <summary>
		/// Initializes a new instance of the <see cref="DocumentCategoryInstance"/> class using the specified <paramref name="domInstance"/> for initializing the object.
		/// </summary>
		/// <param name="domInstance">The <see cref="DomInstance"/> object that provides data for initializing the <see cref="DocumentCategoryInstance"/>. If the section is <c>null</c>, the constructor will not perform any initialization.</param>
		public DocumentCategoryInstance(DomInstance domInstance) : base(domInstance)
		{
			if (!domInstance.DomDefinitionId.Equals(SlcDocumenthubIds.Definitions.DocumentCategory))
				throw new ArgumentException($"The given domInstance, is not of type '{nameof(SlcDocumenthubIds.Definitions.DocumentCategory)}'", nameof(domInstance));
			InitializeProperties();
			AfterLoad();
		}

		/// <summary>
		/// Gets or sets the CategoryInfo section of the DOM Instance.
		/// </summary>
		public CategoryInfoSection CategoryInfo { get; set; }

		public static explicit operator DocumentCategoryInstance(DomInstance instance)
		{
			return new DocumentCategoryInstance(instance);
		}

		/// <summary>
		/// Creates a deep copy of the current <see cref="DocumentCategoryInstance"/>.
		/// </summary>
		/// <returns>A new <see cref="DocumentCategoryInstance"/> object that is a deep copy of this instance.</returns>
		public DocumentCategoryInstance Clone()
		{
			return new DocumentCategoryInstance((DomInstance)this.ToInstance().Clone());
		}

		/// <summary>
		/// Creates a duplicate of the current <see cref="DocumentCategoryInstance"/> with a new id.
		/// </summary>
		/// <returns>A new <see cref="DocumentCategoryInstance"/> object that is a copy of this instance but with a different id.</returns>
		public DocumentCategoryInstance Duplicate()
		{
			var instance = (DomInstance)this.ToInstance().Clone();
			instance.ID = new DomInstanceId(Guid.NewGuid())
			{ ModuleId = ModuleId };
			foreach (var section in instance.Sections)
			{
				section.ID = new Skyline.DataMiner.Net.Sections.SectionID(Guid.NewGuid());
			}

			return new DocumentCategoryInstance(instance);
		}

		/// <inheritdoc />
		protected sealed override DomInstance InternalToInstance()
		{
			domInstance.Sections.Clear();
			domInstance.Sections.Add(CategoryInfo.ToSection());
			return domInstance;
		}

		/// <inheritdoc />
		public sealed override void Save(DomHelper helper)
		{
			var exist = helper.DomInstances.Read(DomInstanceExposers.Id.Equal(domInstance.ID)).FirstOrDefault();
			var instance = ToInstance();
			if (exist == null)
			{
				domInstance = helper.DomInstances.Create(instance);
			}
			else
			{
				domInstance = helper.DomInstances.Update(instance);
			}
		}

		protected sealed override void InitializeProperties()
		{
			var _categoryInfo = domInstance.Sections.FirstOrDefault(section => section.SectionDefinitionID.Equals(SlcDocumenthubIds.Sections.CategoryInfo.Id));
			if (_categoryInfo is null)
			{
				CategoryInfo = new CategoryInfoSection();
			}
			else
			{
				CategoryInfo = new CategoryInfoSection(_categoryInfo);
			}
		}
	}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the DOM Code Generator automation script.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace DomHelpers.SlcDocumenthub
{
	using System;
	using System.Collections.Generic;
	using System.Collections.ObjectModel;
	using System.Linq;
	using Skyline.DataMiner.Net.Apps.DataMinerObjectModel;
	using Skyline.DataMiner.Net.Apps.Sections.Sections;
	using Skyline.DataMiner.Net.Messages;
	using Skyline.DataMiner.Net.Sections;

	/// <summary>
	/// Represents a wrapper class for accessing a DOMSourceInfoSection section.
	/// The <see cref="DOMSourceInfoSection"/> class provides simplified access to the data and functionality of the underlying DOM section, allowing for easier manipulation and retrieval of data from DOM.
	/// </summary>
	public partial class DOMSourceInfoSection : DomSectionBase
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="DOMSourceInfoSection"/> class. Creates an empty <see cref="DOMSourceInfoSection"/> object with default settings.
		/// </summary>
		public DOMSourceInfoSection() : base(SlcDocumenthubIds.Sections.DOMSourceInfo.Id)
		{
		}

		/// <summary>
		/// Initializes a new instance of the <see cref="DOMSourceInfoSection"/> class using the specified <paramref name="section"/> for initializing the object.
		/// </summary>
		/// <param name="section">The <see cref="Section"/> object that provides data for initializing the <see cref="DOMSourceInfoSection"/>. If the section is <c>null</c>, the constructor will not perform any initialization.</param>
		public DOMSourceInfoSection(Section section) : base(section, SlcDocumenthubIds.Sections.DOMSourceInfo.Id)
		{
		}

		/// <summary>
		/// Gets or sets the Name field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public String Name
		{
			get
			{
				var wrapper = section.GetValue<String>(SlcDocumenthubIds.Sections.DOMSourceInfo.Name);
				if (wrapper != null)
				{
					return (String)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcDocumenthubIds.Sections.DOMSourceInfo.Name);
				}
				else
				{
					section.AddOrUpdateValue(SlcDocumenthubIds.Sections.DOMSourceInfo.Name, (String)value);
				}
			}
		}

		/// <summary>
		/// Gets or sets the Module field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public String Module
		{
			get
			{
				var wrapper = section.GetValue<String>(SlcDocumenthubIds.Sections.DOMSourceInfo.Module);
				if (wrapper != null)
				{
					return (String)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcDocumenthubIds.Sections.DOMSourceInfo.Module);
				}
				else
				{
					section.AddOrUpdateValue(SlcDocumenthubIds.Sections.DOMSourceInfo.Module, (String)value);
				}
			}
		}

		/// <summary>
		/// Gets or sets the NetworkSharePath field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public String NetworkSharePath
		{
			get
			{
				var wrapper = section.GetValue<String>(SlcDocumenthubIds.Sections.DOMSourceInfo.NetworkSharePath);
				if (wrapper != null)
				{
					return (String)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcDocumenthubIds.Sections.DOMSourceInfo.NetworkSharePath);
				}
				else
				{
					section.AddOrUpdateValue(SlcDocumenthubIds.Sections.DOMSourceInfo.NetworkSharePath, (String)value);
				}
			}
		}

		/// <summary>
		/// Gets or sets the Credential field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public String Credential
		{
			get
			{
				var wrapper = section.GetValue<String>(SlcDocumenthubIds.Sections.DOMSourceInfo.Credential);
				if (wrapper != null)
				{
					return (String)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcDocumenthubIds.Sections.DOMSourceInfo.Credential);
				}
				else
				{
					section.AddOrUpdateValue(SlcDocumenthubIds.Sections.DOMSourceInfo.Credential, (String)value);
				}
			}
		}

		/// <summary>
		/// Creates a deep copy of the current <see cref="DOMSourceInfoSection"/>.
		/// </summary>
		/// <returns>A new <see cref="DOMSourceInfoSection"/> object that is a deep copy of this section.</returns>
		public DOMSourceInfoSection Clone()
		{
			return new DOMSourceInfoSection((Section)this.ToSection().Clone());
		}

		/// <summary>
		/// Creates a duplicate of the current <see cref="DOMSourceInfoSection"/> with a new id.
		/// </summary>
		/// <returns>A new <see cref="DOMSourceInfoSection"/> object that is a copy of this section but with a different id.</returns>
		public DOMSourceInfoSection Duplicate()
		{
			var section = (Section)this.ToSection().Clone();
			section.ID = new SectionID(Guid.NewGuid());
			return new DOMSourceInfoSection(section);
		}

		/// <inheritdoc />
		protected override Section InternalToSection()
		{
			if (section.GetValue<String>(SlcDocumenthubIds.Sections.DOMSourceInfo.Name) == null)
				throw new InvalidOperationException("'Name' is required. Please fill it in before saving, or mark it as optional with the DOM Editor.");
			if (section.GetValue<String>(SlcDocumenthubIds.Sections.DOMSourceInfo.Module) == null)
				throw new InvalidOperationException("'Module' is required. Please fill it in before saving, or mark it as optional with the DOM Editor.");
			if (section.GetValue<String>(SlcDocumenthubIds.Sections.DOMSourceInfo.NetworkSharePath) == null)
				throw new InvalidOperationException("'NetworkSharePath' is required. Please fill it in before saving, or mark it as optional with the DOM Editor.");
			if (section.GetValue<String>(SlcDocumenthubIds.Sections.DOMSourceInfo.Credential) == null)
				throw new InvalidOperationException("'Credential' is required. Please fill it in before saving, or mark it as optional with the DOM Editor.");
			return section;
		}
	}

	/// <summary>
	/// Represents a wrapper class for accessing a CategoryInfoSection section.
	/// The <see cref="CategoryInfoSection"/> class provides simplified access to the data and functionality of the underlying DOM section, allowing for easier manipulation and retrieval of data from DOM.
	/// </summary>
	public partial class CategoryInfoSection : DomSectionBase
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="CategoryInfoSection"/> class. Creates an empty <see cref="CategoryInfoSection"/> object with default settings.
		/// </summary>
		public CategoryInfoSection() : base(SlcDocumenthubIds.Sections.CategoryInfo.Id)
		{
		}

		/// <summary>
		/// Initializes a new instance of the <see cref="CategoryInfoSection"/> class using the specified <paramref name="section"/> for initializing the object.
		/// </summary>
		/// <param name="section">The <see cref="Section"/> object that provides data for initializing the <see cref="CategoryInfoSection"/>. If the section is <c>null</c>, the constructor will not perform any initialization.</param>
		public CategoryInfoSection(Section section) : base(section, SlcDocumenthubIds.Sections.CategoryInfo.Id)
		{
		}

		/// <summary>
		/// Gets or sets the Name field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public String Name
		{
			get
			{
				var wrapper = section.GetValue<String>(SlcDocumenthubIds.Sections.CategoryInfo.Name);
				if (wrapper != null)
				{
					return (String)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcDocumenthubIds.Sections.CategoryInfo.Name);
				}
				else
				{
					section.AddOrUpdateValue(SlcDocumenthubIds.Sections.CategoryInfo.Name, (String)value);
				}
			}
		}

		/// <summary>
		/// Gets or sets the Uploadpath field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public String Uploadpath
		{
			get
			{
				var wrapper = section.GetValue<String>(SlcDocumenthubIds.Sections.CategoryInfo.Uploadpath);
				if (wrapper != null)
				{
					return (String)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcDocumenthubIds.Sections.CategoryInfo.Uploadpath);
				}
				else
				{
					section.AddOrUpdateValue(SlcDocumenthubIds.Sections.CategoryInfo.Uploadpath, (String)value);
				}
			}
		}

		/// <summary>
		/// Gets or sets the Description field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public String Description
		{
			get
			{
				var wrapper = section.GetValue<String>(SlcDocumenthubIds.Sections.CategoryInfo.Description);
				if (wrapper != null)
				{
					return (String)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcDocumenthubIds.Sections.CategoryInfo.Description);
				}
				else
				{
					section.AddOrUpdateValue(SlcDocumenthubIds.Sections.CategoryInfo.Description, (String)value);
				}
			}
		}

		/// <summary>
		/// Gets or sets the Storagetype field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public SlcDocumenthubIds.Enums.Storagetype? Storagetype
		{
			get
			{
				var wrapper = section.GetValue<Int32>(SlcDocumenthubIds.Sections.CategoryInfo.Storagetype);
				if (wrapper != null)
				{
					return (SlcDocumenthubIds.Enums.Storagetype?)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcDocumenthubIds.Sections.CategoryInfo.Storagetype);
				}
				else
				{
					section.AddOrUpdateValue(SlcDocumenthubIds.Sections.CategoryInfo.Storagetype, (Int32)value);
				}
			}
		}

		/// <summary>
		/// Gets or sets the Extensions field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public String Extensions
		{
			get
			{
				var wrapper = section.GetValue<String>(SlcDocumenthubIds.Sections.CategoryInfo.Extensions);
				if (wrapper != null)
				{
					return (String)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcDocumenthubIds.Sections.CategoryInfo.Extensions);
				}
				else
				{
					section.AddOrUpdateValue(SlcDocumenthubIds.Sections.CategoryInfo.Extensions, (String)value);
				}
			}
		}

		/// <summary>
		/// Gets or sets the Isdefault field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public Boolean? Isdefault
		{
			get
			{
				var wrapper = section.GetValue<Boolean>(SlcDocumenthubIds.Sections.CategoryInfo.Isdefault);
				if (wrapper != null)
				{
					return (Boolean?)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcDocumenthubIds.Sections.CategoryInfo.Isdefault);
				}
				else
				{
					section.AddOrUpdateValue(SlcDocumenthubIds.Sections.CategoryInfo.Isdefault, (Boolean)value);
				}
			}
		}

		/// <summary>
		/// Gets or sets the Definition field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public String Definition
		{
			get
			{
				var wrapper = section.GetValue<String>(SlcDocumenthubIds.Sections.CategoryInfo.Definition);
				if (wrapper != null)
				{
					return (String)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcDocumenthubIds.Sections.CategoryInfo.Definition);
				}
				else
				{
					section.AddOrUpdateValue(SlcDocumenthubIds.Sections.CategoryInfo.Definition, (String)value);
				}
			}
		}

		/// <summary>
		/// Gets or sets the Domsource field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public Guid? Domsource
		{
			get
			{
				var wrapper = section.GetValue<Guid>(SlcDocumenthubIds.Sections.CategoryInfo.Domsource);
				if (wrapper != null)
				{
					return (Guid?)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcDocumenthubIds.Sections.CategoryInfo.Domsource);
				}
				else
				{
					section.AddOrUpdateValue(SlcDocumenthubIds.Sections.CategoryInfo.Domsource, (Guid)value);
				}
			}
		}

		/// <summary>
		/// Creates a deep copy of the current <see cref="CategoryInfoSection"/>.
		/// </summary>
		/// <returns>A new <see cref="CategoryInfoSection"/> object that is a deep copy of this section.</returns>
		public CategoryInfoSection Clone()
		{
			return new CategoryInfoSection((Section)this.ToSection().Clone());
		}

		/// <summary>
		/// Creates a duplicate of the current <see cref="CategoryInfoSection"/> with a new id.
		/// </summary>
		/// <returns>A new <see cref="CategoryInfoSection"/> object that is a copy of this section but with a different id.</returns>
		public CategoryInfoSection Duplicate()
		{
			var section = (Section)this.ToSection().Clone();
			section.ID = new SectionID(Guid.NewGuid());
			return new CategoryInfoSection(section);
		}

		/// <inheritdoc />
		protected override Section InternalToSection()
		{
			if (section.GetValue<String>(SlcDocumenthubIds.Sections.CategoryInfo.Name) == null)
				throw new InvalidOperationException("'Name' is required. Please fill it in before saving, or mark it as optional with the DOM Editor.");
			if (section.GetValue<String>(SlcDocumenthubIds.Sections.CategoryInfo.Uploadpath) == null)
				throw new InvalidOperationException("'Uploadpath' is required. Please fill it in before saving, or mark it as optional with the DOM Editor.");
			if (section.GetValue<Int32>(SlcDocumenthubIds.Sections.CategoryInfo.Storagetype) == null)
				throw new InvalidOperationException("'Storagetype' is required. Please fill it in before saving, or mark it as optional with the DOM Editor.");
			if (section.GetValue<String>(SlcDocumenthubIds.Sections.CategoryInfo.Extensions) == null)
				throw new InvalidOperationException("'Extensions' is required. Please fill it in before saving, or mark it as optional with the DOM Editor.");
			return section;
		}
	}

	/// <summary>
	/// Represents a wrapper class for accessing a ConfigurationSection section.
	/// The <see cref="ConfigurationSection"/> class provides simplified access to the data and functionality of the underlying DOM section, allowing for easier manipulation and retrieval of data from DOM.
	/// </summary>
	public partial class ConfigurationSection : DomSectionBase
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="ConfigurationSection"/> class. Creates an empty <see cref="ConfigurationSection"/> object with default settings.
		/// </summary>
		public ConfigurationSection() : base(SlcDocumenthubIds.Sections.Configuration.Id)
		{
		}

		/// <summary>
		/// Initializes a new instance of the <see cref="ConfigurationSection"/> class using the specified <paramref name="section"/> for initializing the object.
		/// </summary>
		/// <param name="section">The <see cref="Section"/> object that provides data for initializing the <see cref="ConfigurationSection"/>. If the section is <c>null</c>, the constructor will not perform any initialization.</param>
		public ConfigurationSection(Section section) : base(section, SlcDocumenthubIds.Sections.Configuration.Id)
		{
		}

		/// <summary>
		/// Gets or sets the ClientID field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public String ClientID
		{
			get
			{
				var wrapper = section.GetValue<String>(SlcDocumenthubIds.Sections.Configuration.ClientID);
				if (wrapper != null)
				{
					return (String)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcDocumenthubIds.Sections.Configuration.ClientID);
				}
				else
				{
					section.AddOrUpdateValue(SlcDocumenthubIds.Sections.Configuration.ClientID, (String)value);
				}
			}
		}

		/// <summary>
		/// Gets or sets the SiteURL field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public String SiteURL
		{
			get
			{
				var wrapper = section.GetValue<String>(SlcDocumenthubIds.Sections.Configuration.SiteURL);
				if (wrapper != null)
				{
					return (String)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcDocumenthubIds.Sections.Configuration.SiteURL);
				}
				else
				{
					section.AddOrUpdateValue(SlcDocumenthubIds.Sections.Configuration.SiteURL, (String)value);
				}
			}
		}

		/// <summary>
		/// Gets or sets the ClientSecret field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public String ClientSecret
		{
			get
			{
				var wrapper = section.GetValue<String>(SlcDocumenthubIds.Sections.Configuration.ClientSecret);
				if (wrapper != null)
				{
					return (String)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcDocumenthubIds.Sections.Configuration.ClientSecret);
				}
				else
				{
					section.AddOrUpdateValue(SlcDocumenthubIds.Sections.Configuration.ClientSecret, (String)value);
				}
			}
		}

		/// <summary>
		/// Gets or sets the DocumentLibraryName field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public String DocumentLibraryName
		{
			get
			{
				var wrapper = section.GetValue<String>(SlcDocumenthubIds.Sections.Configuration.DocumentLibraryName);
				if (wrapper != null)
				{
					return (String)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcDocumenthubIds.Sections.Configuration.DocumentLibraryName);
				}
				else
				{
					section.AddOrUpdateValue(SlcDocumenthubIds.Sections.Configuration.DocumentLibraryName, (String)value);
				}
			}
		}

		/// <summary>
		/// Gets or sets the Status field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public SlcDocumenthubIds.Enums.Status? Status
		{
			get
			{
				var wrapper = section.GetValue<Int32>(SlcDocumenthubIds.Sections.Configuration.Status);
				if (wrapper != null)
				{
					return (SlcDocumenthubIds.Enums.Status?)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcDocumenthubIds.Sections.Configuration.Status);
				}
				else
				{
					section.AddOrUpdateValue(SlcDocumenthubIds.Sections.Configuration.Status, (Int32)value);
				}
			}
		}

		/// <summary>
		/// Gets or sets the TenantID field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public String TenantID
		{
			get
			{
				var wrapper = section.GetValue<String>(SlcDocumenthubIds.Sections.Configuration.TenantID);
				if (wrapper != null)
				{
					return (String)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcDocumenthubIds.Sections.Configuration.TenantID);
				}
				else
				{
					section.AddOrUpdateValue(SlcDocumenthubIds.Sections.Configuration.TenantID, (String)value);
				}
			}
		}

		/// <summary>
		/// Creates a deep copy of the current <see cref="ConfigurationSection"/>.
		/// </summary>
		/// <returns>A new <see cref="ConfigurationSection"/> object that is a deep copy of this section.</returns>
		public ConfigurationSection Clone()
		{
			return new ConfigurationSection((Section)this.ToSection().Clone());
		}

		/// <summary>
		/// Creates a duplicate of the current <see cref="ConfigurationSection"/> with a new id.
		/// </summary>
		/// <returns>A new <see cref="ConfigurationSection"/> object that is a copy of this section but with a different id.</returns>
		public ConfigurationSection Duplicate()
		{
			var section = (Section)this.ToSection().Clone();
			section.ID = new SectionID(Guid.NewGuid());
			return new ConfigurationSection(section);
		}
	}
}
