//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Skyline.DataMiner.SDM.CodeGenerator package.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Skyline.DataMiner.DocumentHub.SDM.Models
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using System.Runtime.CompilerServices;
    using Skyline.DataMiner.Net.Messages.SLDataGateway;
    using Skyline.DataMiner.SDM;
    using Skyline.DataMiner.SDM.Exposers;
    using SLDataGateway.API.Querying;
    using SLDataGateway.API.Types.Querying;

    public static partial class DocumentCategoryExposers
    {
        public static readonly Exposer<Skyline.DataMiner.DocumentHub.SDM.Models.DocumentCategory, string> Identifier = new Exposer<Skyline.DataMiner.DocumentHub.SDM.Models.DocumentCategory, string>((obj) => obj.Identifier, "Identifier");
        public static readonly Exposer<Skyline.DataMiner.DocumentHub.SDM.Models.DocumentCategory, string> Name = new Exposer<Skyline.DataMiner.DocumentHub.SDM.Models.DocumentCategory, string>((obj) => obj.Name, "Name");
        public static readonly Exposer<Skyline.DataMiner.DocumentHub.SDM.Models.DocumentCategory, string> Description = new Exposer<Skyline.DataMiner.DocumentHub.SDM.Models.DocumentCategory, string>((obj) => obj.Description, "Description");
        public static readonly Exposer<Skyline.DataMiner.DocumentHub.SDM.Models.DocumentCategory, string> UploadPath = new Exposer<Skyline.DataMiner.DocumentHub.SDM.Models.DocumentCategory, string>((obj) => obj.UploadPath, "UploadPath");
        public static readonly Exposer<Skyline.DataMiner.DocumentHub.SDM.Models.DocumentCategory, Skyline.DataMiner.Utils.DocumentHub.API.DataHelpers.SlcDocumenthubIds.Enums.Storagetype> StorageType = new Exposer<Skyline.DataMiner.DocumentHub.SDM.Models.DocumentCategory, Skyline.DataMiner.Utils.DocumentHub.API.DataHelpers.SlcDocumenthubIds.Enums.Storagetype>((obj) => obj.StorageType, "StorageType");
        public static readonly Exposer<Skyline.DataMiner.DocumentHub.SDM.Models.DocumentCategory, string> Extensions = new Exposer<Skyline.DataMiner.DocumentHub.SDM.Models.DocumentCategory, string>((obj) => obj.Extensions, "Extensions");
        public static readonly Exposer<Skyline.DataMiner.DocumentHub.SDM.Models.DocumentCategory, bool> IsDefault = new Exposer<Skyline.DataMiner.DocumentHub.SDM.Models.DocumentCategory, bool>((obj) => obj.IsDefault, "IsDefault");
        public static readonly Exposer<Skyline.DataMiner.DocumentHub.SDM.Models.DocumentCategory, Skyline.DataMiner.SDM.SdmObjectReference<Skyline.DataMiner.DocumentHub.SDM.Models.DomSource>> DOMSource = new Exposer<Skyline.DataMiner.DocumentHub.SDM.Models.DocumentCategory, Skyline.DataMiner.SDM.SdmObjectReference<Skyline.DataMiner.DocumentHub.SDM.Models.DomSource>>((obj) => obj.DOMSource, "DOMSource");
        public static readonly Exposer<Skyline.DataMiner.DocumentHub.SDM.Models.DocumentCategory, string> Definition = new Exposer<Skyline.DataMiner.DocumentHub.SDM.Models.DocumentCategory, string>((obj) => obj.Definition, "Definition");
    }
}