//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Skyline.DataMiner.SDM.CodeGenerator package.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Skyline.DataMiner.DocumentHub.SDM.Models
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using System.Runtime.CompilerServices;
    using Skyline.DataMiner.Net.Messages.SLDataGateway;
    using Skyline.DataMiner.SDM;
    using Skyline.DataMiner.SDM.Exposers;
    using SLDataGateway.API.Querying;
    using SLDataGateway.API.Types.Querying;

    public static partial class DomSourceExposers
    {
        public static readonly Exposer<Skyline.DataMiner.DocumentHub.SDM.Models.DomSource, string> Identifier = new Exposer<Skyline.DataMiner.DocumentHub.SDM.Models.DomSource, string>((obj) => obj.Identifier, "Identifier");
        public static readonly Exposer<Skyline.DataMiner.DocumentHub.SDM.Models.DomSource, string> Name = new Exposer<Skyline.DataMiner.DocumentHub.SDM.Models.DomSource, string>((obj) => obj.Name, "Name");
        public static readonly Exposer<Skyline.DataMiner.DocumentHub.SDM.Models.DomSource, string> Module = new Exposer<Skyline.DataMiner.DocumentHub.SDM.Models.DomSource, string>((obj) => obj.Module, "Module");
        public static readonly Exposer<Skyline.DataMiner.DocumentHub.SDM.Models.DomSource, string> NetworkSharePath = new Exposer<Skyline.DataMiner.DocumentHub.SDM.Models.DomSource, string>((obj) => obj.NetworkSharePath, "NetworkSharePath");
        public static readonly Exposer<Skyline.DataMiner.DocumentHub.SDM.Models.DomSource, string> Credential = new Exposer<Skyline.DataMiner.DocumentHub.SDM.Models.DomSource, string>((obj) => obj.Credential, "Credential");
    }
}