//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Skyline.DataMiner.SDM.CodeGenerator package.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Skyline.DataMiner.Utils.DocumentHub.SDM.Models
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using System.Runtime.CompilerServices;
    using Skyline.DataMiner.DocumentHub.SDM.Models;
    using Skyline.DataMiner.Net.Messages.SLDataGateway;
    using Skyline.DataMiner.SDM;
    using Skyline.DataMiner.SDM.Exposers;
    using SLDataGateway.API.Querying;
    using SLDataGateway.API.Types.Querying;

    public static partial class SharePointConfigurationExposers
    {
        public static readonly Exposer<SharePointConfiguration, string> Identifier = new Exposer<SharePointConfiguration, string>((obj) => obj.Identifier, "Identifier");
        public static readonly Exposer<SharePointConfiguration, string> TenantID = new Exposer<SharePointConfiguration, string>((obj) => obj.TenantID, "TenantID");
        public static readonly Exposer<SharePointConfiguration, string> ClientID = new Exposer<SharePointConfiguration, string>((obj) => obj.ClientID, "ClientID");
        public static readonly Exposer<SharePointConfiguration, string> ClientSecret = new Exposer<SharePointConfiguration, string>((obj) => obj.ClientSecret, "ClientSecret");
        public static readonly Exposer<SharePointConfiguration, string> SiteURL = new Exposer<SharePointConfiguration, string>((obj) => obj.SiteURL, "SiteURL");
        public static readonly Exposer<SharePointConfiguration, string> DocumentLibraryName = new Exposer<SharePointConfiguration, string>((obj) => obj.DocumentLibraryName, "DocumentLibraryName");
    }
}