//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Skyline.DataMiner.SDM.CodeGenerator package.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Skyline.DataMiner.Solutions.DocumentHub.SDM
{
    using global::Skyline.DataMiner.Net;
    using global::Skyline.DataMiner.Net.Apps.DataMinerObjectModel;
    using global::Skyline.DataMiner.Net.Helper;
    using global::Skyline.DataMiner.Net.ManagerStore;
    using global::Skyline.DataMiner.Net.Messages.SLDataGateway;
    using global::Skyline.DataMiner.SDM;
    using Skyline.DataMiner.Solutions.DocumentHub.SDM.Maps;
    using Skyline.DataMiner.Net.Messages;
    using Skyline.DataMiner.Net.Sections;
    using Skyline.DataMiner.Solutions.DocumentHub.SDM.Models;
    using SLDataGateway.API.Querying;
    using SLDataGateway.API.Types.Querying;
    using System;
    using System.Collections.Generic;
    using System.Linq;

    internal partial class DocumentCategoryDomRepository : IBulkRepository<DocumentCategory>
    {
        private readonly IConnection connection;
        private readonly DomHelper helper;
        public DocumentCategoryDomRepository(IConnection connection)
        {
            this.connection = connection;
            this.helper = new DomHelper(connection.HandleMessages, DocumentCategoryDomMapper.ModuleId);
        }

        // TODO: before creating the Category, check if the DOM Source reference is added, create it if necessary.
        public DocumentCategory Create(DocumentCategory createObject)
        {
            if (createObject is null)
            {
                throw new ArgumentNullException(nameof(createObject));
            }

            var instance = ToInstance(createObject);
            instance = helper.DomInstances.Create(instance);
            return FromInstance(instance);
        }

        public IReadOnlyCollection<DocumentCategory> Create(IEnumerable<DocumentCategory> createObjects)
        {
            if (createObjects is null || !createObjects.Any())
            {
                return Array.Empty<DocumentCategory>();
            }

            // Check if some of the objects already exist
            var existing = new HashSet<string>();
            foreach (var batch in createObjects.Batch(500))
            {
                existing.UnionWith(Read(new ORFilterElement<DocumentCategory>(batch.Select(obj => DocumentCategoryExposers.Identifier.Equal(obj.Identifier)).ToArray())).Select(obj => obj.Identifier));
            }

            // Create the remainder
            var SuccessfulItems = new List<DocumentCategory>();
            var failures = new Dictionary<string, Exception>();
            var objects = createObjects.Where(obj => !existing.Contains(obj.Identifier)).ToDictionary(obj => obj.Identifier);
            foreach (var batch in createObjects.Select(ToInstance).Batch(helper.DomInstances.MaxAmountBulkOperation))
            {
                helper.DomInstances.TryCreateOrUpdate(batch.ToList(), out var result);
                foreach (var failure in result.UnsuccessfulIds)
                {
                    failures.Add(failure.Id.ToString(), new CrudFailedException(result.TraceDataPerItem[failure]));
                }

                foreach (var success in result.SuccessfulItems)
                {
                    SuccessfulItems.Add(FromInstance(success));
                }
            }

            // If everything went fine, return the successful creations
            if (!existing.Any() && !failures.Any())
            {
                return SuccessfulItems;
            }

            // Otherwise, build and throw an exception
            var exceptionBuilder = new SdmBulkCrudException<DocumentCategory>.Builder();
            foreach (var obj in createObjects)
            {
                if (existing.Contains(obj.Identifier))
                {
                    exceptionBuilder.AddFailed(obj, new SdmCrudException<DocumentCategory>(obj, $"Could not create DocumentCategory with guid: '{obj.Identifier}', it already exists."));
                    continue;
                }

                if (failures.ContainsKey(obj.Identifier))
                {
                    exceptionBuilder.AddFailed(obj, failures[obj.Identifier]);
                    continue;
                }

                exceptionBuilder.AddSuccessful(obj);
            }

            throw exceptionBuilder.Build();
        }

        public IReadOnlyCollection<DocumentCategory> CreateOrUpdate(IEnumerable<DocumentCategory> items)
        {
            if (items is null || !items.Any())
            {
                return Array.Empty<DocumentCategory>();
            }

            var successful = new List<DocumentCategory>();
            var exceptionBuilder = new SdmBulkCrudException<DocumentCategory>.Builder();
            var objects = items.ToDictionary(obj => obj.Identifier);
            foreach (var batch in items.Select(ToInstance).Batch(helper.DomInstances.MaxAmountBulkOperation))
            {
                helper.DomInstances.TryCreateOrUpdate(batch.ToList(), out var result);
                foreach (var failure in result.UnsuccessfulIds)
                {
                    exceptionBuilder.AddFailed(objects[failure.Id.ToString()], new CrudFailedException(result.TraceDataPerItem[failure]));
                }

                foreach (var success in result.SuccessfulItems)
                {
                    var item = FromInstance(success);
                    exceptionBuilder.AddSuccessful(item);
                    successful.Add(item);
                }
            }

            if (exceptionBuilder.HasFailure)
            {
                throw exceptionBuilder.Build();
            }

            return successful;
        }

        public long Count(FilterElement<DocumentCategory> filter)
        {
            if (filter is null)
            {
                throw new ArgumentNullException(nameof(filter));
            }

            var domFilter = TranslateFullFilter(filter);
            domFilter = domFilter.AND(DomInstanceExposers.DomDefinitionId.Equal(DocumentCategoryDomMapper.DomDefinitionId.Id));
            return helper.DomInstances.Count(domFilter);
        }

        public long Count(IQuery<DocumentCategory> query)
        {
            if (query is null)
            {
                throw new ArgumentNullException(nameof(query));
            }

            var domFilter = TranslateFullFilter(query.Filter);
            domFilter = domFilter.AND(DomInstanceExposers.DomDefinitionId.Equal(DocumentCategoryDomMapper.DomDefinitionId.Id));
            var domOrder = TranslateFullOrderBy(query.Order);
            var domQuery = query.WithFilter(domFilter).WithOrder(domOrder);
            return helper.DomInstances.Count(domQuery);
        }

        public IEnumerable<DocumentCategory> Read(FilterElement<DocumentCategory> filter)
        {
            if (filter is null)
            {
                throw new ArgumentNullException(nameof(filter));
            }

            var domFilter = TranslateFullFilter(filter);
            return Read(domFilter);
        }

        public IEnumerable<DocumentCategory> Read(IQuery<DocumentCategory> query)
        {
            if (query is null)
            {
                throw new ArgumentNullException(nameof(query));
            }

            var domFilter = TranslateFullFilter(query.Filter);
            var domOrder = TranslateFullOrderBy(query.Order);
            var domQuery = query.WithFilter(domFilter).WithOrder(domOrder);
            return Read(domQuery);
        }

        public IEnumerable<IPagedResult<DocumentCategory>> ReadPaged(FilterElement<DocumentCategory> filter)
        {
            return ReadPaged(filter, 500);
        }

        public IEnumerable<IPagedResult<DocumentCategory>> ReadPaged(FilterElement<DocumentCategory> filter, int pageSize)
        {
            if (filter is null)
            {
                throw new ArgumentNullException(nameof(filter));
            }

            if (pageSize <= 0)
            {
                throw new ArgumentOutOfRangeException(nameof(pageSize), "The page size must be 1 or higher");
            }

            var domFilter = TranslateFullFilter(filter);
            var paging = ReadPaged(domFilter, pageSize).GetEnumerator();
            var moveNext = paging.MoveNext();
            var i = 0;
            while (moveNext)
            {
                var page = paging.Current.ToList();
                moveNext = paging.MoveNext();
                var result = new PagedResult<DocumentCategory>(page, i, pageSize, moveNext);
                yield return result;
                i++;
            }
        }

        public IEnumerable<IPagedResult<DocumentCategory>> ReadPaged(IQuery<DocumentCategory> query)
        {
            return ReadPaged(query, 500);
        }

        public IEnumerable<IPagedResult<DocumentCategory>> ReadPaged(IQuery<DocumentCategory> query, int pageSize)
        {
            if (query is null)
            {
                throw new ArgumentNullException(nameof(query));
            }

            if (pageSize <= 0)
            {
                throw new ArgumentOutOfRangeException(nameof(pageSize), "The page size must be 1 or higher");
            }

            var domFilter = TranslateFullFilter(query.Filter);
            var domOrder = TranslateFullOrderBy(query.Order);
            var domQuery = query.WithFilter(domFilter).WithOrder(domOrder);
            var paging = ReadPaged(domQuery, pageSize).GetEnumerator();
            var moveNext = paging.MoveNext();
            var i = 0;
            while (moveNext)
            {
                var page = paging.Current.ToList();
                moveNext = paging.MoveNext();
                var result = new PagedResult<DocumentCategory>(page, i, pageSize, moveNext);
                yield return result;
                i++;
            }
        }

        public DocumentCategory Update(DocumentCategory updateObject)
        {
            if (updateObject is null)
            {
                throw new ArgumentNullException(nameof(updateObject));
            }

            var instance = ToInstance(updateObject);
            instance = helper.DomInstances.Update(instance);
            return FromInstance(instance);
        }

        public IReadOnlyCollection<DocumentCategory> Update(IEnumerable<DocumentCategory> updateObjects)
        {
            if (updateObjects is null || !updateObjects.Any())
            {
                return Array.Empty<DocumentCategory>();
            }

            // Check if which objects already exist
            var existing = new HashSet<string>();
            foreach (var batch in updateObjects.Batch(500))
            {
                existing.UnionWith(Read(new ORFilterElement<DocumentCategory>(batch.Select(obj => DocumentCategoryExposers.Identifier.Equal(obj.Identifier)).ToArray())).Select(obj => obj.Identifier));
            }

            // Update the existing objects
            var successfulItems = new List<DocumentCategory>();
            var failures = new Dictionary<string, Exception>();
            var objects = updateObjects.Where(obj => existing.Contains(obj.Identifier)).ToDictionary(obj => obj.Identifier);
            foreach (var batch in updateObjects.Select(ToInstance).Batch(helper.DomInstances.MaxAmountBulkOperation))
            {
                helper.DomInstances.TryCreateOrUpdate(batch.ToList(), out var result);
                foreach (var failure in result.UnsuccessfulIds)
                {
                    failures.Add(failure.Id.ToString(), new CrudFailedException(result.TraceDataPerItem[failure]));
                }

                foreach (var success in result.SuccessfulItems)
                {
                    successfulItems.Add(FromInstance(success));
                }
            }

            // Check for failures and build exception if needed
            var exceptionBuilder = new SdmBulkCrudException<DocumentCategory>.Builder();
            foreach (var obj in updateObjects)
            {
                if (!existing.Contains(obj.Identifier))
                {
                    exceptionBuilder.AddFailed(obj, new SdmCrudException<DocumentCategory>(obj, "Could not update a non existing DocumentCategory"));
                    continue;
                }

                if (failures.ContainsKey(obj.Identifier))
                {
                    exceptionBuilder.AddFailed(obj, failures[obj.Identifier]);
                    continue;
                }

                exceptionBuilder.AddSuccessful(obj);
            }

            if (exceptionBuilder.HasFailure)
            {
                throw exceptionBuilder.Build();
            }

            return successfulItems;
        }

        public void Delete(DocumentCategory deleteObject)
        {
            if (deleteObject is null)
            {
                throw new ArgumentNullException(nameof(deleteObject));
            }

            var instance = ToInstance(deleteObject);
            helper.DomInstances.Delete(instance);
        }

        public void Delete(IEnumerable<DocumentCategory> deleteObjects)
        {
            if (deleteObjects is null || !deleteObjects.Any())
            {
                return;
            }

            var exceptionBuilder = new SdmBulkCrudException<DocumentCategory>.Builder();
            var objects = deleteObjects.ToDictionary(obj => obj.Identifier);
            foreach (var batch in deleteObjects.Select(ToInstance).Batch(helper.DomInstances.MaxAmountBulkOperation))
            {
                helper.DomInstances.TryDelete(batch.ToList(), out var result);
                foreach (var failure in result.UnsuccessfulIds)
                {
                    exceptionBuilder.AddFailed(objects[failure.Id.ToString()], new CrudFailedException(result.TraceDataPerItem[failure]));
                }

                foreach (var success in result.SuccessfulIds)
                {
                    exceptionBuilder.AddSuccessful(objects[success.Id.ToString()]);
                }
            }

            if (exceptionBuilder.HasFailure)
            {
                throw exceptionBuilder.Build();
            }
        }

        private IEnumerable<DocumentCategory> Read(FilterElement<DomInstance> domFilter)
        {
            if (domFilter is null)
            {
                throw new ArgumentNullException(nameof(domFilter));
            }

            domFilter = domFilter.AND(DomInstanceExposers.DomDefinitionId.Equal(DocumentCategoryDomMapper.DomDefinitionId.Id));
            var domInstances = helper.DomInstances.Read(domFilter);
            return domInstances.Select(FromInstance);
        }

        private IEnumerable<DocumentCategory> Read(IQuery<DomInstance> domQuery)
        {
            if (domQuery is null)
            {
                throw new ArgumentNullException(nameof(domQuery));
            }

            var domFilter = domQuery.Filter.AND(DomInstanceExposers.DomDefinitionId.Equal(DocumentCategoryDomMapper.DomDefinitionId.Id));
            domQuery = domQuery.WithFilter(domFilter);
            var domInstances = helper.DomInstances.Read(domQuery);
            return domInstances.Select(FromInstance);
        }

        private IEnumerable<IEnumerable<DocumentCategory>> ReadPaged(FilterElement<DomInstance> domFilter, int pageSize)
        {
            if (domFilter is null)
            {
                throw new ArgumentNullException(nameof(domFilter));
            }

            domFilter = domFilter.AND(DomInstanceExposers.DomDefinitionId.Equal(DocumentCategoryDomMapper.DomDefinitionId.Id));
            var pagingHelper = helper.DomInstances.PreparePaging(domFilter, pageSize);
            while (pagingHelper.MoveToNextPage())
            {
                yield return pagingHelper.GetCurrentPage().Select(FromInstance);
            }
        }

        private IEnumerable<IEnumerable<DocumentCategory>> ReadPaged(IQuery<DomInstance> domQuery, int pageSize)
        {
            if (domQuery is null)
            {
                throw new ArgumentNullException(nameof(domQuery));
            }

            var domFilter = domQuery.Filter.AND(DomInstanceExposers.DomDefinitionId.Equal(DocumentCategoryDomMapper.DomDefinitionId.Id));
            domQuery = domQuery.WithFilter(domFilter);
            var pagingHelper = helper.DomInstances.PreparePaging(domQuery, pageSize);
            while (pagingHelper.MoveToNextPage())
            {
                yield return pagingHelper.GetCurrentPage().Select(FromInstance);
            }
        }

        private FilterElement<DomInstance> TranslateFullFilter(FilterElement<DocumentCategory> filter)
        {
            if (filter is null)
            {
                throw new ArgumentNullException(nameof(filter));
            }

            FilterElement<DomInstance> translated;
            if (filter is ANDFilterElement<DocumentCategory> and)
            {
                translated = new ANDFilterElement<DomInstance>(and.subFilters.Select(TranslateFullFilter).ToArray());
            }
            else if (filter is ORFilterElement<DocumentCategory> or)
            {
                translated = new ORFilterElement<DomInstance>(or.subFilters.Select(TranslateFullFilter).ToArray());
            }
            else if (filter is NOTFilterElement<DocumentCategory> not)
            {
                translated = new NOTFilterElement<DomInstance>(TranslateFullFilter(not));
            }
            else if (filter is TRUEFilterElement<DocumentCategory>)
            {
                translated = new TRUEFilterElement<DomInstance>();
            }
            else if (filter is FALSEFilterElement<DocumentCategory>)
            {
                translated = new FALSEFilterElement<DomInstance>();
            }
            else if (filter is ManagedFilterIdentifier managedFilter)
            {
                translated = TranslateFilter(managedFilter);
            }
            else
            {
                throw new NotSupportedException($"Unsupported filter: {filter}");
            }

            return translated;
        }

        private IOrderBy TranslateFullOrderBy(IOrderBy order)
        {
            if (order is null)
            {
                throw new ArgumentNullException(nameof(order));
            }

            var translatedElements = new List<IOrderByElement>();
            foreach (var orderByElement in order.Elements)
            {
                var translated = TranslateOrderBy(orderByElement);
                translatedElements.Add(translated);
            }

            return new OrderBy(translatedElements);
        }

        private FilterElement<DomInstance> TranslateFilter(ManagedFilterIdentifier managedFilter)
        {
            if (managedFilter is null)
            {
                throw new ArgumentNullException(nameof(managedFilter));
            }

            var fieldName = managedFilter.getFieldName().fieldName;
            var comparer = managedFilter.getComparer();
            var value = managedFilter.getValue();
            var translated = CreateFilter(fieldName, comparer, value);
            return translated;
        }

        private IOrderByElement TranslateOrderBy(IOrderByElement orderByElement)
        {
            if (orderByElement is null)
            {
                throw new ArgumentNullException(nameof(orderByElement));
            }

            var fieldName = orderByElement.Exposer.fieldName;
            var sortOrder = orderByElement.SortOrder;
            var naturalSort = orderByElement.Options.NaturalSort;
            var translated = CreateOrderBy(fieldName, sortOrder, naturalSort);
            return translated;
        }

        private DocumentCategory FromInstance(DomInstance instance)
        {
            var obj = new DocumentCategory
            {
                Identifier = instance.ID.Id.ToString()
            };
            var _documentcategorypropertiesSection = instance.Sections.FirstOrDefault(s => s.SectionDefinitionID.Equals(Skyline.DataMiner.Solutions.DocumentHub.SDM.Maps.DocumentCategoryDomMapper.DocumentCategoryProperties.SectionDefinitionId));
            if (_documentcategorypropertiesSection != default)
            {
                var _name = _documentcategorypropertiesSection.GetValue<string>(Skyline.DataMiner.Solutions.DocumentHub.SDM.Maps.DocumentCategoryDomMapper.DocumentCategoryProperties.Name);
                if (_name != null)
                {
                    obj.Name = _name.Value;
                }

                var _description = _documentcategorypropertiesSection.GetValue<string>(Skyline.DataMiner.Solutions.DocumentHub.SDM.Maps.DocumentCategoryDomMapper.DocumentCategoryProperties.Description);
                if (_description != null)
                {
                    obj.Description = _description.Value;
                }

                var _uploadpath = _documentcategorypropertiesSection.GetValue<string>(Skyline.DataMiner.Solutions.DocumentHub.SDM.Maps.DocumentCategoryDomMapper.DocumentCategoryProperties.UploadPath);
                if (_uploadpath != null)
                {
                    obj.UploadPath = _uploadpath.Value;
                }

                var _storagetype = _documentcategorypropertiesSection.GetValue<int>(Skyline.DataMiner.Solutions.DocumentHub.SDM.Maps.DocumentCategoryDomMapper.DocumentCategoryProperties.StorageType);
                if (_storagetype != null)
                {
                    obj.StorageType = (Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.StorageType)_storagetype.Value;
                }

                var _extensions = _documentcategorypropertiesSection.GetValue<string>(Skyline.DataMiner.Solutions.DocumentHub.SDM.Maps.DocumentCategoryDomMapper.DocumentCategoryProperties.Extensions);
                if (_extensions != null)
                {
                    obj.Extensions = _extensions.Value;
                }

                var _isdefault = _documentcategorypropertiesSection.GetValue<bool>(Skyline.DataMiner.Solutions.DocumentHub.SDM.Maps.DocumentCategoryDomMapper.DocumentCategoryProperties.IsDefault);
                if (_isdefault != null)
                {
                    obj.IsDefault = _isdefault.Value;
                }

                var _domsource = _documentcategorypropertiesSection.GetValue<string>(Skyline.DataMiner.Solutions.DocumentHub.SDM.Maps.DocumentCategoryDomMapper.DocumentCategoryProperties.DOMSource);
                if (_domsource != null)
                {
                    obj.DOMSource = new Skyline.DataMiner.SDM.SdmObjectReference<Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.DomSource>(Convert.ToString(_domsource.Value));
                }

                var _definition = _documentcategorypropertiesSection.GetValue<string>(Skyline.DataMiner.Solutions.DocumentHub.SDM.Maps.DocumentCategoryDomMapper.DocumentCategoryProperties.Definition);
                if (_definition != null)
                {
                    obj.Definition = _definition.Value;
                }
            }

            return obj;
        }

        private DomInstance ToInstance(DocumentCategory obj)
        {
            Guid id = default(Guid);
            if (!String.IsNullOrEmpty(obj.Identifier))
            {
                id = Guid.Parse(obj.Identifier);
            }
            else
            {
                id = Guid.NewGuid();
            }

            var instance = new DomInstance
            {
                DomDefinitionId = Skyline.DataMiner.Solutions.DocumentHub.SDM.Maps.DocumentCategoryDomMapper.DomDefinitionId,
                ID = new DomInstanceId(id)
                {
                    ModuleId = Skyline.DataMiner.Solutions.DocumentHub.SDM.Maps.DocumentCategoryDomMapper.ModuleId
                }
            };
            var _documentcategoryproperties = new Section(Skyline.DataMiner.Solutions.DocumentHub.SDM.Maps.DocumentCategoryDomMapper.DocumentCategoryProperties.SectionDefinitionId);
            if (obj.Name != default)
            {
                _documentcategoryproperties.AddOrUpdateValue<string>(Skyline.DataMiner.Solutions.DocumentHub.SDM.Maps.DocumentCategoryDomMapper.DocumentCategoryProperties.Name, Convert.ToString(obj.Name));
            }

            if (obj.Description != default)
            {
                _documentcategoryproperties.AddOrUpdateValue<string>(Skyline.DataMiner.Solutions.DocumentHub.SDM.Maps.DocumentCategoryDomMapper.DocumentCategoryProperties.Description, Convert.ToString(obj.Description));
            }

            if (obj.UploadPath != default)
            {
                _documentcategoryproperties.AddOrUpdateValue<string>(Skyline.DataMiner.Solutions.DocumentHub.SDM.Maps.DocumentCategoryDomMapper.DocumentCategoryProperties.UploadPath, Convert.ToString(obj.UploadPath));
            }

            _documentcategoryproperties.AddOrUpdateValue<int>(Skyline.DataMiner.Solutions.DocumentHub.SDM.Maps.DocumentCategoryDomMapper.DocumentCategoryProperties.StorageType, (int)obj.StorageType);
            if (obj.Extensions != default)
            {
                _documentcategoryproperties.AddOrUpdateValue<string>(Skyline.DataMiner.Solutions.DocumentHub.SDM.Maps.DocumentCategoryDomMapper.DocumentCategoryProperties.Extensions, Convert.ToString(obj.Extensions));
            }

            if (obj.IsDefault != default)
            {
                _documentcategoryproperties.AddOrUpdateValue<bool>(Skyline.DataMiner.Solutions.DocumentHub.SDM.Maps.DocumentCategoryDomMapper.DocumentCategoryProperties.IsDefault, (bool)obj.IsDefault);
            }

            if (obj.DOMSource != default)
            {
                _documentcategoryproperties.AddOrUpdateValue<string>(Skyline.DataMiner.Solutions.DocumentHub.SDM.Maps.DocumentCategoryDomMapper.DocumentCategoryProperties.DOMSource, obj.DOMSource.Identifier);
            }

            if (obj.Definition != default)
            {
                _documentcategoryproperties.AddOrUpdateValue<string>(Skyline.DataMiner.Solutions.DocumentHub.SDM.Maps.DocumentCategoryDomMapper.DocumentCategoryProperties.Definition, Convert.ToString(obj.Definition));
            }

            instance.Sections.Add(_documentcategoryproperties);
            return instance;
        }

        private FilterElement<DomInstance> CreateFilter(string fieldName, Comparer comparer, object value)
        {
            switch (fieldName)
            {
                case "Identifier":
                    return FilterElementFactory.Create<DomInstance>(DomInstanceExposers.Id, comparer, Guid.Parse((string)value));
                case "Name":
                    return new DynamicManagedListFilter<DomInstance, object>(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.Solutions.DocumentHub.SDM.Maps.DocumentCategoryDomMapper.DocumentCategoryProperties.Name), comparer, (string)value);
                case "Description":
                    return new DynamicManagedListFilter<DomInstance, object>(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.Solutions.DocumentHub.SDM.Maps.DocumentCategoryDomMapper.DocumentCategoryProperties.Description), comparer, (string)value);
                case "UploadPath":
                    return new DynamicManagedListFilter<DomInstance, object>(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.Solutions.DocumentHub.SDM.Maps.DocumentCategoryDomMapper.DocumentCategoryProperties.UploadPath), comparer, (string)value);
                case "StorageType":
                    return new DynamicManagedListFilter<DomInstance, object>(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.Solutions.DocumentHub.SDM.Maps.DocumentCategoryDomMapper.DocumentCategoryProperties.StorageType), comparer, (int)(Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.StorageType)value);
                case "Extensions":
                    return new DynamicManagedListFilter<DomInstance, object>(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.Solutions.DocumentHub.SDM.Maps.DocumentCategoryDomMapper.DocumentCategoryProperties.Extensions), comparer, (string)value);
                case "IsDefault":
                    return new DynamicManagedListFilter<DomInstance, object>(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.Solutions.DocumentHub.SDM.Maps.DocumentCategoryDomMapper.DocumentCategoryProperties.IsDefault), comparer, (bool)value);
                case "DOMSource":
                    return new DynamicManagedListFilter<DomInstance, object>(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.Solutions.DocumentHub.SDM.Maps.DocumentCategoryDomMapper.DocumentCategoryProperties.DOMSource), comparer, Skyline.DataMiner.SDM.SdmObjectReference<Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.DomSource>.Convert(value).Identifier);
                case "Definition":
                    return new DynamicManagedListFilter<DomInstance, object>(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.Solutions.DocumentHub.SDM.Maps.DocumentCategoryDomMapper.DocumentCategoryProperties.Definition), comparer, (string)value);
                default:
                    throw new NotImplementedException();
            }
        }

        private IOrderByElement CreateOrderBy(string fieldName, SortOrder sortOrder, bool naturalSort = false)
        {
            switch (fieldName)
            {
                case "Identifier":
                    return OrderByElementFactory.Create(DomInstanceExposers.Id, sortOrder, naturalSort);
                case "Name":
                    return OrderByElementFactory.Create(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.Solutions.DocumentHub.SDM.Maps.DocumentCategoryDomMapper.DocumentCategoryProperties.Name), sortOrder, naturalSort);
                case "Description":
                    return OrderByElementFactory.Create(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.Solutions.DocumentHub.SDM.Maps.DocumentCategoryDomMapper.DocumentCategoryProperties.Description), sortOrder, naturalSort);
                case "UploadPath":
                    return OrderByElementFactory.Create(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.Solutions.DocumentHub.SDM.Maps.DocumentCategoryDomMapper.DocumentCategoryProperties.UploadPath), sortOrder, naturalSort);
                case "StorageType":
                    return OrderByElementFactory.Create(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.Solutions.DocumentHub.SDM.Maps.DocumentCategoryDomMapper.DocumentCategoryProperties.StorageType), sortOrder, naturalSort);
                case "Extensions":
                    return OrderByElementFactory.Create(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.Solutions.DocumentHub.SDM.Maps.DocumentCategoryDomMapper.DocumentCategoryProperties.Extensions), sortOrder, naturalSort);
                case "IsDefault":
                    return OrderByElementFactory.Create(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.Solutions.DocumentHub.SDM.Maps.DocumentCategoryDomMapper.DocumentCategoryProperties.IsDefault), sortOrder, naturalSort);
                case "DOMSource":
                    return OrderByElementFactory.Create(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.Solutions.DocumentHub.SDM.Maps.DocumentCategoryDomMapper.DocumentCategoryProperties.DOMSource), sortOrder, naturalSort);
                case "Definition":
                    return OrderByElementFactory.Create(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.Solutions.DocumentHub.SDM.Maps.DocumentCategoryDomMapper.DocumentCategoryProperties.Definition), sortOrder, naturalSort);
                default:
                    throw new NotImplementedException();
            }
        }
    }
}
