//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Skyline.DataMiner.SDM.CodeGenerator package.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skyline.DataMiner.Solutions.DocumentHub.SDM
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using Skyline.DataMiner.Net;
    using Skyline.DataMiner.Net.Apps.DataMinerObjectModel;
    using Skyline.DataMiner.Net.Apps.Sections.Sections;
    using Skyline.DataMiner.Net.Helper;
    using Skyline.DataMiner.Net.ManagerStore;
    using Skyline.DataMiner.Net.Messages;
    using Skyline.DataMiner.Net.Messages.SLDataGateway;
    using Skyline.DataMiner.Net.Sections;
    using Skyline.DataMiner.Net.SubscriptionFilters;
    using Skyline.DataMiner.SDM;
    using SLDataGateway.API.Querying;
    using SLDataGateway.API.Types.Querying;

    internal sealed partial class DocumentCategoryDomRepository_Middleware : Skyline.DataMiner.SDM.IBulkRepository<Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.DocumentCategory>
    {
        private readonly Skyline.DataMiner.SDM.IBulkRepository<Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.DocumentCategory> _inner;
        private readonly IMiddlewareMarker<Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.DocumentCategory> _middleware;

        public DocumentCategoryDomRepository_Middleware(Skyline.DataMiner.SDM.IBulkRepository<Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.DocumentCategory> inner, IMiddlewareMarker<Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.DocumentCategory> middleware)
        {
            _inner = inner ?? throw new ArgumentNullException(nameof(inner));
            _middleware = middleware;
        }

        public IEnumerable<IPagedResult<Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.DocumentCategory>> ReadPaged(FilterElement<Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.DocumentCategory> filter)
        {
            if (_middleware is IPageableMiddleware<Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.DocumentCategory> middleware)
            {
                return middleware.OnReadPaged(filter, _inner.ReadPaged);
            }
            else
            {
                return _inner.ReadPaged(filter);
            }
        }

        public IEnumerable<IPagedResult<Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.DocumentCategory>> ReadPaged(IQuery<Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.DocumentCategory> query)
        {
            if (_middleware is IPageableMiddleware<Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.DocumentCategory> middleware)
            {
                return middleware.OnReadPaged(query, _inner.ReadPaged);
            }
            else
            {
                return _inner.ReadPaged(query);
            }
        }

        public IEnumerable<IPagedResult<Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.DocumentCategory>> ReadPaged(FilterElement<Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.DocumentCategory> filter, int pageSize)
        {
            if (_middleware is IPageableMiddleware<Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.DocumentCategory> middleware)
            {
                return middleware.OnReadPaged(filter, pageSize, _inner.ReadPaged);
            }
            else
            {
                return _inner.ReadPaged(filter, pageSize);
            }
        }

        public IEnumerable<IPagedResult<Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.DocumentCategory>> ReadPaged(IQuery<Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.DocumentCategory> query, int pageSize)
        {
            if (_middleware is IPageableMiddleware<Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.DocumentCategory> middleware)
            {
                return middleware.OnReadPaged(query, pageSize, _inner.ReadPaged);
            }
            else
            {
                return _inner.ReadPaged(query, pageSize);
            }
        }

        public IEnumerable<Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.DocumentCategory> Read(FilterElement<Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.DocumentCategory> filter)
        {
            if (_middleware is IReadableMiddleware<Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.DocumentCategory> middleware)
            {
                return middleware.OnRead(filter, _inner.Read);
            }
            else
            {
                return _inner.Read(filter);
            }
        }

        public IEnumerable<Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.DocumentCategory> Read(IQuery<Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.DocumentCategory> query)
        {
            if (_middleware is IReadableMiddleware<Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.DocumentCategory> middleware)
            {
                return middleware.OnRead(query, _inner.Read);
            }
            else
            {
                return _inner.Read(query);
            }
        }

        public long Count(FilterElement<Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.DocumentCategory> filter)
        {
            if (_middleware is ICountableMiddleware<Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.DocumentCategory> middleware)
            {
                return middleware.OnCount(filter, _inner.Count);
            }
            else
            {
                return _inner.Count(filter);
            }
        }

        public long Count(IQuery<Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.DocumentCategory> query)
        {
            if (_middleware is ICountableMiddleware<Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.DocumentCategory> middleware)
            {
                return middleware.OnCount(query, _inner.Count);
            }
            else
            {
                return _inner.Count(query);
            }
        }

        public IReadOnlyCollection<Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.DocumentCategory> Create(IEnumerable<Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.DocumentCategory> oToCreate)
        {
            if (_middleware is IBulkCreatableMiddleware<Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.DocumentCategory> middleware)
            {
                return middleware.OnCreate(oToCreate, _inner.Create);
            }
            else
            {
                return _inner.Create(oToCreate);
            }
        }

        public Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.DocumentCategory Create(Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.DocumentCategory oToCreate)
        {
            if (_middleware is ICreatableMiddleware<Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.DocumentCategory> middleware)
            {
                return middleware.OnCreate(oToCreate, _inner.Create);
            }
            else
            {
                return _inner.Create(oToCreate);
            }
        }

        public IReadOnlyCollection<Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.DocumentCategory> Update(IEnumerable<Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.DocumentCategory> oToUpdate)
        {
            if (_middleware is IBulkUpdatableMiddleware<Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.DocumentCategory> middleware)
            {
                return middleware.OnUpdate(oToUpdate, _inner.Update);
            }
            else
            {
                return _inner.Update(oToUpdate);
            }
        }

        public Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.DocumentCategory Update(Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.DocumentCategory oToUpdate)
        {
            if (_middleware is IUpdatableMiddleware<Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.DocumentCategory> middleware)
            {
                return middleware.OnUpdate(oToUpdate, _inner.Update);
            }
            else
            {
                return _inner.Update(oToUpdate);
            }
        }

        public void Delete(IEnumerable<Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.DocumentCategory> oToDelete)
        {
            if (_middleware is IBulkDeletableMiddleware<Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.DocumentCategory> middleware)
            {
                middleware.OnDelete(oToDelete, _inner.Delete);
            }
            else
            {
                _inner.Delete(oToDelete);
            }
        }

        public void Delete(Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.DocumentCategory oToDelete)
        {
            if (_middleware is IDeletableMiddleware<Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.DocumentCategory> middleware)
            {
                middleware.OnDelete(oToDelete, _inner.Delete);
            }
            else
            {
                _inner.Delete(oToDelete);
            }
        }
        public System.Collections.Generic.IReadOnlyCollection<Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.DocumentCategory> CreateOrUpdate(System.Collections.Generic.IEnumerable<Skyline.DataMiner.Solutions.DocumentHub.SDM.Models.DocumentCategory> oToCreateOrUpdate)
        {
            return _inner.CreateOrUpdate(oToCreateOrUpdate);
        }

    }
}
